if(${_MSDK_BOARD_NAME_} STREQUAL "KIT_EFM32GG11_STARTER")
    set(BOARD_PATH "include/boards/board_kit_efm32gg11_starter")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
