if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_LPCXPRESSO43S67_DEVELOPMENT")
    set(BOARD_PATH "include/boards/board_lpcxpresso43s67_development")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
