if(${_MSDK_BOARD_NAME_} STREQUAL "KIT_DISCOVERY_WITH_STM32H735IG_MCU")
    set(BOARD_PATH "include/boards/board_kit_discovery_with_stm32h735ig_mcu")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
