if(${_MSDK_BOARD_NAME_} STREQUAL "KIT_EFR32BG_BLUETOOTH_MODULE_STARTER")
    set(BOARD_PATH "include/boards/kit_efr32bg_bluetooth_module_starter")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
