if(${_MSDK_BOARD_NAME_} STREQUAL "PIC18F46J50_FS_USB_DEMO_BOARD")
    set(BOARD_PATH "include/boards/board_pic18f46j50_fs_usb_demo")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
