if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_APM32F403R_MICROEVB")
    set(BOARD_PATH "include/boards/board_apm32f403r_microevb")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
