if(${_MSDK_BOARD_NAME_} STREQUAL "SAM_IOT_WX_V2_DEVELOPMENT_BOARD")
    set(BOARD_PATH "include/boards/board_sam_iot_wx_v2")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
