if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_STARTERKIT_A31G346RLN")
    set(BOARD_PATH "include/boards/board_starterkit_a31g346rln")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
