if(${_MSDK_BOARD_NAME_} STREQUAL "STARTERKIT_A31G324RLN")
    set(BOARD_PATH "include/boards/board_starterkit_a31g324rln")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
