if(${_MSDK_BOARD_NAME_} STREQUAL "CLICKER_4_FOR_MK64FN1M0VLL12")
    set(BOARD_PATH "include/boards/clicker_4_for_mk64fn1m0vll12")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
