if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_LPCXPRESSO18S37_DEVELOPMENT")
    set(BOARD_PATH "include/boards/board_lpcxpresso18s37_development")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
