if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_FREEDOM_FOR_KL16_KL26")
    set(BOARD_PATH "include/boards/board_freedom_for_kl16_kl26")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
