if(${_MSDK_BOARD_NAME_} STREQUAL "STARTERKIT_A31C122KYN")
    set(BOARD_PATH "include/boards/board_starterkit_a31c122kyn")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
