if(${_MSDK_BOARD_NAME_} STREQUAL "PIC32CX_SG41_CURIOSITY_ULTRA_EVALUATION_BOARD")
    set(BOARD_PATH "include/boards/board_pic32cx_sg41_curiosity_ultra")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
