if(${_MSDK_BOARD_NAME_} STREQUAL "DSPICDEM_2_DEVELOPMENT_BOARD")
    set(BOARD_PATH "include/boards/board_dspicdem_2_development")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET TRUE)
endif()
