/****************************************************************************
**
** Copyright (C) 2026 MikroElektronika d.o.o.
** Contact: https://www.mikroe.com/contact
**
** This file is part of the mikroSDK package
**
** Commercial License Usage
**
** Licensees holding valid commercial NECTO compilers AI licenses may use this
** file in accordance with the commercial license agreement provided with the
** Software or, alternatively, in accordance with the terms contained in
** a written agreement between you and The MikroElektronika Company.
** For licensing terms and conditions see
** https://www.mikroe.com/legal/software-license-agreement.
** For further information use the contact form at
** https://www.mikroe.com/contact.
**
**
** GNU Lesser General Public License Usage
**
** Alternatively, this file may be used for
** non-commercial projects under the terms of the GNU Lesser
** General Public License version 3 as published by the Free Software
** Foundation: https://www.gnu.org/licenses/lgpl-3.0.html.
**
** The above copyright notice and this permission notice shall be
** included in all copies or substantial portions of the Software.
**
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
** EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
** OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
** IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
** DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
** OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
** OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
**
****************************************************************************/
/*!
 * @file  mcu_definitions.h
 * @brief MCU specific pin and module definitions.
 */

#ifndef _MCU_DEFINITIONS_H_
#define _MCU_DEFINITIONS_H_

#include "mcu_reg_addresses.h"
#include "can_definitions.h"
//#include "xc.h"
//ADC
#define HAL_LL_RA0_AN0_ANCON0_BIT 0
#define HAL_LL_RA0_AN0_ANCON0 0
#define HAL_LL_RA1_AN1_ANCON0_BIT 1
#define HAL_LL_RA1_AN1_ANCON0 1
#define HAL_LL_RA2_AN2_ANCON0_BIT 2
#define HAL_LL_RA2_AN2_ANCON0 2
#define HAL_LL_RA3_AN3_ANCON0_BIT 3
#define HAL_LL_RA3_AN3_ANCON0 3
#define HAL_LL_RA5_AN4_ANCON0_BIT 4
#define HAL_LL_RA5_AN4_ANCON0 4
#define HAL_LL_RB0_AN12_ANCON1_BIT 4
#define HAL_LL_RB0_AN12_ANCON1 12
#define HAL_LL_RB1_AN10_ANCON1_BIT 2
#define HAL_LL_RB1_AN10_ANCON1 10
#define HAL_LL_RB2_AN8_ANCON1_BIT 0
#define HAL_LL_RB2_AN8_ANCON1 8
#define HAL_LL_RB3_AN9_ANCON1_BIT 1
#define HAL_LL_RB3_AN9_ANCON1 9
#define HAL_LL_RC2_AN11_ANCON1_BIT 3
#define HAL_LL_RC2_AN11_ANCON1 11


#define HAL_LL_ANCON1_ADDRESS 0xF49U
#define HAL_LL_ANCON0_ADDRESS 0xF48U


#define ADC_MODULE 1
#define ADC_MODULE_COUNT 1
//EOF ADC

//I2C
#define I2C1_SCL_RC3
#define I2C1_SDA_RC4


#define I2C_MODULE_1 1
#define I2C_MODULE_2 2


#define HAL_LL_I2C_PPS_ENABLED true
//EOF I2C

//UART
#define UART1_TX_RC6
#define UART2_TX_RA0
#define UART2_TX_RA1
#define UART2_TX_RA5
#define UART2_TX_RB0
#define UART2_TX_RB1
#define UART2_TX_RB2
#define UART2_TX_RB3
#define UART2_TX_RB4
#define UART2_TX_RB5
#define UART2_TX_RB6
#define UART2_TX_RB7
#define UART2_TX_RC0
#define UART2_TX_RC1
#define UART2_TX_RC2
#define UART2_TX_RC3
#define UART2_TX_RC4
#define UART2_TX_RC5
#define UART2_TX_RC6
#define UART2_TX_RC7

#define UART1_RX_RC7
#define UART2_RX_RA0
#define UART2_RX_RA1
#define UART2_RX_RA5
#define UART2_RX_RB0
#define UART2_RX_RB1
#define UART2_RX_RB2
#define UART2_RX_RB3
#define UART2_RX_RB4
#define UART2_RX_RB5
#define UART2_RX_RB6
#define UART2_RX_RB7
#define UART2_RX_RC0
#define UART2_RX_RC1
#define UART2_RX_RC2
#define UART2_RX_RC3
#define UART2_RX_RC4
#define UART2_RX_RC5
#define UART2_RX_RC6
#define UART2_RX_RC7


#define UART_MODULE_1 1
#define UART_MODULE_2 2

#define UART_MODULE_COUNT 2

#define HAL_LL_UART_PPS_ENABLED true
//EOF UART

//SPI
#define SPI1_MISO_RC4
#define SPI1_MOSI_RC5
#define SPI1_SCK_RC3
#define SPI2_MISO_RA0
#define SPI2_MISO_RA1
#define SPI2_MISO_RA5
#define SPI2_MISO_RB0
#define SPI2_MISO_RB1
#define SPI2_MISO_RB2
#define SPI2_MISO_RB3
#define SPI2_MISO_RB4
#define SPI2_MISO_RB5
#define SPI2_MISO_RB6
#define SPI2_MISO_RB7
#define SPI2_MISO_RC0
#define SPI2_MISO_RC1
#define SPI2_MISO_RC2
#define SPI2_MISO_RC3
#define SPI2_MISO_RC4
#define SPI2_MISO_RC5
#define SPI2_MISO_RC6
#define SPI2_MISO_RC7
#define SPI2_MOSI_RA0
#define SPI2_MOSI_RA1
#define SPI2_MOSI_RA5
#define SPI2_MOSI_RB0
#define SPI2_MOSI_RB1
#define SPI2_MOSI_RB2
#define SPI2_MOSI_RB3
#define SPI2_MOSI_RB4
#define SPI2_MOSI_RB5
#define SPI2_MOSI_RB6
#define SPI2_MOSI_RB7
#define SPI2_MOSI_RC0
#define SPI2_MOSI_RC1
#define SPI2_MOSI_RC2
#define SPI2_MOSI_RC3
#define SPI2_MOSI_RC4
#define SPI2_MOSI_RC5
#define SPI2_MOSI_RC6
#define SPI2_MOSI_RC7
#define SPI2_SCK_RA0
#define SPI2_SCK_RA1
#define SPI2_SCK_RA5
#define SPI2_SCK_RB0
#define SPI2_SCK_RB1
#define SPI2_SCK_RB2
#define SPI2_SCK_RB3
#define SPI2_SCK_RB4
#define SPI2_SCK_RB5
#define SPI2_SCK_RB6
#define SPI2_SCK_RB7
#define SPI2_SCK_RC0
#define SPI2_SCK_RC1
#define SPI2_SCK_RC2
#define SPI2_SCK_RC3
#define SPI2_SCK_RC4
#define SPI2_SCK_RC5
#define SPI2_SCK_RC6
#define SPI2_SCK_RC7


#define SPI_MODULE_1 1
#define SPI_MODULE_2 2



#define SPI_MODULE_COUNT 2

#define HAL_LL_SPI_PPS_ENABLED true
//EOF SPI

//PWM
#define PWM_CCP1_RA0
#define PWM_CCP1_RA1
#define PWM_CCP1_RA5
#define PWM_CCP1_RB0
#define PWM_CCP1_RB1
#define PWM_CCP1_RB2
#define PWM_CCP1_RB3
#define PWM_CCP1_RB4
#define PWM_CCP1_RB5
#define PWM_CCP1_RB6
#define PWM_CCP1_RB7
#define PWM_CCP1_RC0
#define PWM_CCP1_RC1
#define PWM_CCP1_RC2
#define PWM_CCP1_RC3
#define PWM_CCP1_RC4
#define PWM_CCP1_RC5
#define PWM_CCP1_RC6
#define PWM_CCP1_RC7
#define PWM_CCP2_RA0
#define PWM_CCP2_RA1
#define PWM_CCP2_RA5
#define PWM_CCP2_RB0
#define PWM_CCP2_RB1
#define PWM_CCP2_RB2
#define PWM_CCP2_RB3
#define PWM_CCP2_RB4
#define PWM_CCP2_RB5
#define PWM_CCP2_RB6
#define PWM_CCP2_RB7
#define PWM_CCP2_RC0
#define PWM_CCP2_RC1
#define PWM_CCP2_RC2
#define PWM_CCP2_RC3
#define PWM_CCP2_RC4
#define PWM_CCP2_RC5
#define PWM_CCP2_RC6
#define PWM_CCP2_RC7


#define CCP_MODULE_1 1
#define CCP_MODULE_2 2

#define CCP_MODULE_COUNT 2


#define HAL_LL_TIM_PPS_ENABLED true
//EOF PWM

//IO
#define __RA0_CN
#define __RA1_CN
#define __RA2_CN
#define __RA3_CN
#define __RA5_CN
#define __RA6_CN
#define __RA7_CN
#define __RB0_CN
#define __RB1_CN
#define __RB2_CN
#define __RB3_CN
#define __RB4_CN
#define __RB5_CN
#define __RB6_CN
#define __RB7_CN
#define __RC0_CN
#define __RC1_CN
#define __RC2_CN
#define __RC3_CN
#define __RC4_CN
#define __RC5_CN
#define __RC6_CN
#define __RC7_CN
#define __RD0_CN
#define __RD1_CN
#define __RD2_CN
#define __RD3_CN
#define __RD4_CN
#define __RD5_CN
#define __RD6_CN
#define __RD7_CN
#define __RE0_CN
#define __RE1_CN
#define __RE2_CN
#define __RE3_CN

#define __PORT_A_CN
#define __PORT_B_CN
#define __PORT_C_CN
#define __PORT_D_CN
#define __PORT_E_CN

//EOF IO


// EOF GPIO Register addresses and offsets

// PMD Register addresses
#define HAL_LL_PIE1_ADDRESS 0xF9DU
#define HAL_LL_PIE2_ADDRESS 0xFA0U
#define HAL_LL_PIE3_ADDRESS 0xFA3U
#define HAL_LL_PIR1_ADDRESS 0xF9EU
#define HAL_LL_PIR2_ADDRESS 0xFA1U
#define HAL_LL_PIR3_ADDRESS 0xFA4U
// EOF PMD Register addresses

// I2C and SPI Register addresses
#define HAL_LL_SSP1ADD_ADDRESS 0xFC8U
#define HAL_LL_SSP1BUF_ADDRESS 0xFC9U
#define HAL_LL_SSP1CON1_ADDRESS 0xFC6U
#define HAL_LL_SSP1CON2_ADDRESS 0xFC5U
#define HAL_LL_SSP1STAT_ADDRESS 0xFC7U
#define HAL_LL_SSP2ADD_ADDRESS 0xF74U
#define HAL_LL_SSP2BUF_ADDRESS 0xF75U
#define HAL_LL_SSP2CON1_ADDRESS 0xF72U
#define HAL_LL_SSP2CON2_ADDRESS 0xF71U
#define HAL_LL_SSP2STAT_ADDRESS 0xF73U
#define HAL_LL_SSPBUF_SPI_MASTER_MODULE_1 HAL_LL_SSP1BUF_ADDRESS
#define HAL_LL_SSPBUF_SPI_MASTER_MODULE_2 HAL_LL_SSP2BUF_ADDRESS
#define HAL_LL_SSPCON1_SPI_MASTER_MODULE_1 HAL_LL_SSP1CON1_ADDRESS
#define HAL_LL_SSPCON1_SPI_MASTER_MODULE_2 HAL_LL_SSP2CON1_ADDRESS
#define HAL_LL_SSPSTAT_SPI_MASTER_MODULE_1 HAL_LL_SSP1STAT_ADDRESS
#define HAL_LL_SSPSTAT_SPI_MASTER_MODULE_2 HAL_LL_SSP2STAT_ADDRESS
// EOF I2C and SPI Register addresses

// PMD & PIR Register defines
#define HAL_LL_PIE_MODULE_UART1_ADDRESS HAL_LL_PIE1_ADDRESS
#define HAL_LL_PIE_MODULE_UART2_ADDRESS HAL_LL_PIE3_ADDRESS
#define HAL_LL_PIR_MODULE_I2C1_ADDRESS HAL_LL_PIR1_ADDRESS
#define HAL_LL_PIR_MODULE_I2C2_ADDRESS HAL_LL_PIR3_ADDRESS
#define HAL_LL_PIR_MODULE_UART1_ADDRESS HAL_LL_PIR1_ADDRESS
#define HAL_LL_PIR_MODULE_UART2_ADDRESS HAL_LL_PIR3_ADDRESS
#define HAL_LL_PIR_SSPIF_MODULE_1_BIT 3
#define HAL_LL_PIR_SSPIF_MODULE_2_BIT 7
#define HAL_LL_UART1_RCIF_BIT 5
#define HAL_LL_UART1_TXIF_BIT 4
#define HAL_LL_UART2_RCIF_BIT 5
#define HAL_LL_UART2_TXIF_BIT 4

// EOF PMD & PIR Register defines

// TMR Register addresses
#define HAL_LL_PSTR2CON_ADDRESS 0xFB9U
#define HAL_LL_PSTR1CON_ADDRESS 0xFBFU
#define HAL_LL_CCP1CON_ADDRESS 0xFBAU
#define HAL_LL_CCP2CON_ADDRESS 0xFB4U
#define HAL_LL_PR4_ADDRESS 0xF77U
#define HAL_LL_T0CON_ADDRESS 0xFD5U
#define HAL_LL_T1CON_ADDRESS 0xFCDU
#define HAL_LL_T2CON_ADDRESS 0xFCAU
#define HAL_LL_T3CON_ADDRESS 0xF79U
#define HAL_LL_T4CON_ADDRESS 0xF76U
#define HAL_LL_CCPR1L_ADDRESS 0xFBBU
#define HAL_LL_CCPR2L_ADDRESS 0xFB5U
// EOF TMR Register addresses

// ODCON Register addresses and bit defines
#define HAL_LL_ODCON_NUMERIC
#define HAL_LL_ODCON1_ADDRESS 0xF42U
#define HAL_LL_ODCON1_ECCP1OD_BIT 0
#define HAL_LL_ODCON1_ECCP2OD_BIT 1
#define HAL_LL_ODCON2_ADDRESS 0xF41U
#define HAL_LL_ODCON3_ADDRESS 0xF40U

// EOF ODCON Register addresses and bit defines

// UART Register addresses
#define HAL_LL_BAUDCON1_ADDRESS 0xF7EU
#define HAL_LL_BAUDCON2_ADDRESS 0xF7CU
#define HAL_LL_RCREG1_ADDRESS 0xFAFU
#define HAL_LL_RCREG2_ADDRESS 0xFAAU
#define HAL_LL_RCSTA1_ADDRESS 0xFACU
#define HAL_LL_RCSTA2_ADDRESS 0xF9CU
#define HAL_LL_SPBRG1_ADDRESS 0xFB0U
#define HAL_LL_SPBRG2_ADDRESS 0xFABU
#define HAL_LL_SPBRGH1_ADDRESS 0xF7FU
#define HAL_LL_SPBRGH2_ADDRESS 0xF7DU
#define HAL_LL_TXREG1_ADDRESS 0xFAEU
#define HAL_LL_TXREG2_ADDRESS 0xFA9U
#define HAL_LL_TXSTA1_ADDRESS 0xFADU
#define HAL_LL_TXSTA2_ADDRESS 0xFA8U
// EOF UART Register addresses

// RPOR Register addresses
#define HAL_LL_RPOR0_ADDRESS 0xEC6U
#define HAL_LL_RPOR1_ADDRESS 0xEC7U
#define HAL_LL_RPOR2_ADDRESS 0xEC8U
#define HAL_LL_RPOR3_ADDRESS 0xEC9U
#define HAL_LL_RPOR4_ADDRESS 0xECAU
#define HAL_LL_RPOR5_ADDRESS 0xECBU
#define HAL_LL_RPOR6_ADDRESS 0xECCU
#define HAL_LL_RPOR7_ADDRESS 0xECDU
#define HAL_LL_RPOR8_ADDRESS 0xECEU
#define HAL_LL_RPOR9_ADDRESS 0xECFU
#define HAL_LL_RPOR10_ADDRESS 0xED0U
#define HAL_LL_RPOR11_ADDRESS 0xED1U
#define HAL_LL_RPOR12_ADDRESS 0xED2U
#define HAL_LL_RPOR13_ADDRESS 0xED3U
#define HAL_LL_RPOR14_ADDRESS 0xED4U
#define HAL_LL_RPOR15_ADDRESS 0xED5U
#define HAL_LL_RPOR16_ADDRESS 0xED6U
#define HAL_LL_RPOR17_ADDRESS 0xED7U
#define HAL_LL_RPOR18_ADDRESS 0xED8U
// EOF RPOR Register addresses

// RPINR Register addresses
#define HAL_LL_RPINR1_ADDRESS 0xEE7U
#define HAL_LL_RPINR2_ADDRESS 0xEE8U
#define HAL_LL_RPINR3_ADDRESS 0xEE9U
#define HAL_LL_RPINR4_ADDRESS 0xEEAU
#define HAL_LL_RPINR6_ADDRESS 0xEECU
#define HAL_LL_RPINR7_ADDRESS 0xEEDU
#define HAL_LL_RPINR8_ADDRESS 0xEEEU
#define HAL_LL_RPINR12_ADDRESS 0xEF2U
#define HAL_LL_RPINR13_ADDRESS 0xEF3U
#define HAL_LL_RPINR16_ADDRESS 0xEF6U
#define HAL_LL_RPINR17_ADDRESS 0xEF7U
#define HAL_LL_RPINR21_ADDRESS 0xEFBU
#define HAL_LL_RPINR22_ADDRESS 0xEFCU
#define HAL_LL_RPINR23_ADDRESS 0xEFDU
#define HAL_LL_RPINR24_ADDRESS 0xEFEU
// EOF RPINR Register addresses

// Unlock Register addresses
#define HAL_LL_PPSCON_ADDRESS 0xEFFU
#define HAL_LL_EECON2_ADDRESS 0xFA7U
// EOF Unlock Register addresses


// IRQ defines
#define HAL_LL_INTERRUPT_PRIORITY_LOW 0x0018
#define HAL_LL_INTERRUPT_PRIORITY_HIGH 0x0008
#define HAL_LL_INTERRUPT_PRIORITY HAL_LL_INTERRUPT_PRIORITY_HIGH
#define HAL_LL_IRQ_TX1IE_BIT 4
#define HAL_LL_IRQ_RC1IE_BIT 5
#define HAL_LL_IRQ_TX2IE_BIT 20
#define HAL_LL_IRQ_RC2IE_BIT 21
// EOF IRQ defines


#define I2C1_SCL_RC3
#define I2C1_SCL_RC4


#define I2C2_SCL_RB0
#define I2C2_SCL_RB1
#define I2C2_SCL_RB2
#define I2C2_SCL_RB3
#define I2C2_SCL_RB4
#define I2C2_SCL_RB5
#define I2C2_SCL_RB6
#define I2C2_SCL_RB7
#define I2C2_SCL_RC0
#define I2C2_SCL_RC1
#define I2C2_SCL_RC2
#define I2C2_SCL_RC3
#define I2C2_SCL_RC4
#define I2C2_SCL_RC5
#define I2C2_SCL_RC6
#define I2C2_SCL_RC7
#define I2C2_SCL_RD0
#define I2C2_SCL_RD1
#define I2C2_SCL_RD2
#define I2C2_SCL_RD3
#define I2C2_SCL_RD4
#define I2C2_SCL_RD5
#define I2C2_SCL_RD6
#define I2C2_SCL_RD7
#define I2C2_SDA_RB0
#define I2C2_SDA_RB1
#define I2C2_SDA_RB2
#define I2C2_SDA_RB3
#define I2C2_SDA_RB4
#define I2C2_SDA_RB5
#define I2C2_SDA_RB6
#define I2C2_SDA_RB7
#define I2C2_SDA_RC0
#define I2C2_SDA_RC1
#define I2C2_SDA_RC2
#define I2C2_SDA_RC3
#define I2C2_SDA_RC4
#define I2C2_SDA_RC5
#define I2C2_SDA_RC6
#define I2C2_SDA_RC7

// PPS registers
#define HAL_LL_RA0PPS_ADDRESS 0x201U
#define HAL_LL_RA1PPS_ADDRESS 0x202U
#define HAL_LL_RA2PPS_ADDRESS 0x203U
#define HAL_LL_RA3PPS_ADDRESS 0x204U
#define HAL_LL_RA4PPS_ADDRESS 0x205U
#define HAL_LL_RA5PPS_ADDRESS 0x206U
#define HAL_LL_RA6PPS_ADDRESS 0x207U
#define HAL_LL_RA7PPS_ADDRESS 0x208U
#define HAL_LL_RB0PPS_ADDRESS 0x209U
#define HAL_LL_RB1PPS_ADDRESS 0x20AU
#define HAL_LL_RB2PPS_ADDRESS 0x20BU
#define HAL_LL_RB3PPS_ADDRESS 0x20CU
#define HAL_LL_RB4PPS_ADDRESS 0x20DU
#define HAL_LL_RB5PPS_ADDRESS 0x20EU
#define HAL_LL_RB6PPS_ADDRESS 0x20FU
#define HAL_LL_RB7PPS_ADDRESS 0x210U
#define HAL_LL_RC0PPS_ADDRESS 0x211U
#define HAL_LL_RC1PPS_ADDRESS 0x212U
#define HAL_LL_RC2PPS_ADDRESS 0x213U
#define HAL_LL_RC3PPS_ADDRESS 0x1DF9 // changed
#define HAL_LL_RC4PPS_ADDRESS 0x1DA0 // 
#define HAL_LL_RC5PPS_ADDRESS 0x216U
#define HAL_LL_RC6PPS_ADDRESS 0x217U
#define HAL_LL_RC7PPS_ADDRESS 0x218U
#define HAL_LL_RD0PPS_ADDRESS 0x219U
#define HAL_LL_RD1PPS_ADDRESS 0x21AU
#define HAL_LL_RD2PPS_ADDRESS 0x21BU
#define HAL_LL_RD3PPS_ADDRESS 0x21CU
#define HAL_LL_RD4PPS_ADDRESS 0x21DU
#define HAL_LL_RD5PPS_ADDRESS 0x21EU
#define HAL_LL_RD6PPS_ADDRESS 0x21FU
#define HAL_LL_RD7PPS_ADDRESS 0x220U
#define HAL_LL_RE0PPS_ADDRESS 0x221U
#define HAL_LL_RE1PPS_ADDRESS 0x222U
#define HAL_LL_RE2PPS_ADDRESS 0x223U
#define HAL_LL_RF0PPS_ADDRESS 0x229U
#define HAL_LL_RF1PPS_ADDRESS 0x22AU
#define HAL_LL_RF2PPS_ADDRESS 0x22BU
#define HAL_LL_RF3PPS_ADDRESS 0x22CU
#define HAL_LL_RF4PPS_ADDRESS 0x22DU
#define HAL_LL_RF5PPS_ADDRESS 0x22EU
#define HAL_LL_RF6PPS_ADDRESS 0x22FU
#define HAL_LL_RF7PPS_ADDRESS 0x230U
#define HAL_LL_INT0PPS_ADDRESS 0x23EU
#define HAL_LL_INT1PPS_ADDRESS 0x23FU
#define HAL_LL_INT2PPS_ADDRESS 0x240U
#define HAL_LL_T0CKIPPS_ADDRESS 0x241U
#define HAL_LL_T1CKIPPS_ADDRESS 0x242U
#define HAL_LL_T1GPPS_ADDRESS 0x243U
#define HAL_LL_T3CKIPPS_ADDRESS 0x244U
#define HAL_LL_T3GPPS_ADDRESS 0x245U
#define HAL_LL_T5CKIPPS_ADDRESS 0x246U
#define HAL_LL_T5GPPS_ADDRESS 0x247U
#define HAL_LL_T2INPPS_ADDRESS 0x248U
#define HAL_LL_T4INPPS_ADDRESS 0x249U
#define HAL_LL_T6INPPS_ADDRESS 0x24AU
#define HAL_LL_CCP1PPS_ADDRESS 0x24FU
#define HAL_LL_CCP2PPS_ADDRESS 0x250U
#define HAL_LL_CCP3PPS_ADDRESS 0x251U
#define HAL_LL_PWM1ERSPPS_ADDRESS 0x253U
#define HAL_LL_PWM2ERSPPS_ADDRESS 0x254U
#define HAL_LL_PWM3ERSPPS_ADDRESS 0x255U
#define HAL_LL_PWMIN0PPS_ADDRESS 0x257U
#define HAL_LL_PWMIN1PPS_ADDRESS 0x258U
#define HAL_LL_SMT1WINPPS_ADDRESS 0x259U
#define HAL_LL_SMT1SIGPPS_ADDRESS 0x25AU
#define HAL_LL_CWG1PPS_ADDRESS 0x25BU
#define HAL_LL_CWG2PPS_ADDRESS 0x25CU
#define HAL_LL_CWG3PPS_ADDRESS 0x25DU
#define HAL_LL_MD1CARLPPS_ADDRESS 0x25EU
#define HAL_LL_MD1CARHPPS_ADDRESS 0x25FU
#define HAL_LL_MD1SRCPPS_ADDRESS 0x260U
#define HAL_LL_CLCIN0PPS_ADDRESS 0x261U
#define HAL_LL_CLCIN1PPS_ADDRESS 0x262U
#define HAL_LL_CLCIN2PPS_ADDRESS 0x263U
#define HAL_LL_CLCIN3PPS_ADDRESS 0x264U
#define HAL_LL_CLCIN4PPS_ADDRESS 0x265U
#define HAL_LL_CLCIN5PPS_ADDRESS 0x266U
#define HAL_LL_CLCIN6PPS_ADDRESS 0x267U
#define HAL_LL_CLCIN7PPS_ADDRESS 0x268U
#define HAL_LL_ADACTPPS_ADDRESS 0x269U
#define HAL_LL_SPI1SCKPPS_ADDRESS 0x26AU
#define HAL_LL_SPI1SDIPPS_ADDRESS 0x26BU
#define HAL_LL_SPI1SSPPS_ADDRESS 0x26CU
#define HAL_LL_SPI2SCKPPS_ADDRESS 0x26DU
#define HAL_LL_SPI2SDIPPS_ADDRESS 0x26EU
#define HAL_LL_SPI2SSPPS_ADDRESS 0x26FU
#define HAL_LL_I2C1SDAPPS_ADDRESS 0x1E48 // 
#define HAL_LL_I2C1SCLPPS_ADDRESS 0x1E47 //
#define HAL_LL_I2C2SDAPPS_ADDRESS 0x270U
#define HAL_LL_I2C2SCLPPS_ADDRESS 0x271U
#define HAL_LL_U1RXPPS_ADDRESS 0x272U
#define HAL_LL_U1CTSPPS_ADDRESS 0x273U
#define HAL_LL_U2RXPPS_ADDRESS 0x274U
#define HAL_LL_U2CTSPPS_ADDRESS 0x275U
#define HAL_LL_U3RXPPS_ADDRESS 0x276U
#define HAL_LL_U3CTSPPS_ADDRESS 0x277U
#define HAL_LL_U4RXPPS_ADDRESS 0x278U
#define HAL_LL_U4CTSPPS_ADDRESS 0x279U
#define HAL_LL_U5RXPPS_ADDRESS 0x27AU
#define HAL_LL_U5CTSPPS_ADDRESS 0x27BU


#endif // _MCU_DEFINITIONS_H_
// ------------------------------------------------------------------------- END
