if(${_MSDK_BOARD_NAME_} STREQUAL "STARTERKIT_A34G43AYLN")
    set(BOARD_PATH "include/boards/board_starterkit_a34g43ayln")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
