if(${_MSDK_BOARD_NAME_} STREQUAL "SAM_D10_XPLAINED_MINI")
    set(BOARD_PATH "include/boards/board_samd10_xplained_mini")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
