if(${_MSDK_BOARD_NAME_} STREQUAL "DSPICDEM_80_PIN_STARTER_DEVELOPMENT_BOARD")
    set(BOARD_PATH "include/boards/board_dspicdem_80_pin_starter_development")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
