if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_LAUNCHPAD_FOR_MSPM0G3507_MCU")
    set(BOARD_PATH "include/boards/board_launchpad_for_mspm0g3507_mcu")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
