if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_NUMAKER_HMI_M487D2")
    set(BOARD_PATH "include/boards/board_numaker_hmi_m487d2")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
