if(${_MSDK_BOARD_NAME_} STREQUAL "PIC32MZ_EC_STARTER_KIT")
    set(BOARD_PATH "include/boards/board_pic32mz_ec_starter_kit")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
