if(${_MSDK_BOARD_NAME_} STREQUAL "MICROSTICK_FOR_3V_PIC24F_K_SERIES")
    set(BOARD_PATH "include/boards/board_microstick_for_3v_pic24f_k_series")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET TRUE)
endif()
