if(${_MSDK_BOARD_NAME_} STREQUAL "PIC32MZ_EMBEDDED_GRAPHICS_WITH_EXTERNAL_DRAM_STARTER_KIT")
    set(BOARD_PATH "include/boards/board_pic32mz_embedded_graphics_external")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
