if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_NUMAKER_NUC029SGE")
    set(BOARD_PATH "include/boards/board_numaker_nuc029sge")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
