if(${_MSDK_BOARD_NAME_} STREQUAL "KIT_EFM32_PG1_STARTER")
    set(BOARD_PATH "include/boards/board_kit_efm32_pg1_starter")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
