if(${_MSDK_BOARD_NAME_} STREQUAL "DSPICDEM_NET_CONNECTIVITY_DEVELOPMENT_BOARD")
    set(BOARD_PATH "include/boards/board_dspicdem_net_connectivity_development")
    set(PIM_SOCKET TRUE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
