if(${_MSDK_BOARD_NAME_} STREQUAL "AUDIO_FOR_PIC32_MCUS_DEVELOPMENT_BOARD")
    set(BOARD_PATH "include/boards/board_audio_development_for_pic32")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
endif()
