if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_CURIOSITY_NANO_WITH_PIC18F57Q43")
    set(BOARD_PATH   "include/boards/board_curiosity_nano_with_pic18f57q43")
    set(MCU_CARD  FALSE)
    set(SHIELD  TRUE)
endif()
