if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_FREEDOM_FOR_KV3X_FAMILY")
    set(BOARD_PATH "include/boards/board_freedom_for_kv3x_family")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
