set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "" FORCE)
set(CMAKE_CACHEFILE_DIR "c:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/build-GLCD" CACHE STRING "" FORCE)
set(CMAKE_CACHE_MAJOR_VERSION "3" CACHE STRING "" FORCE)
set(CMAKE_CACHE_MINOR_VERSION "30" CACHE STRING "" FORCE)
set(CMAKE_CACHE_PATCH_VERSION "5" CACHE STRING "" FORCE)
set(CMAKE_COMMAND "C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/bin/cmake.exe" CACHE STRING "" FORCE)
set(CMAKE_CPACK_COMMAND "C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/bin/cpack.exe" CACHE STRING "" FORCE)
set(CMAKE_CTEST_COMMAND "C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/bin/ctest.exe" CACHE STRING "" FORCE)
set(CMAKE_EDIT_COMMAND "C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/bin/cmake-gui.exe" CACHE STRING "" FORCE)
set(CMAKE_EXPORT_COMPILE_COMMANDS "1" CACHE STRING "" FORCE)
set(CMAKE_FIND_PACKAGE_REDIRECTS_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/build-GLCD/CMakeFiles/pkgRedirects" CACHE STRING "" FORCE)
set(CMAKE_GENERATOR "Ninja" CACHE STRING "" FORCE)
set(CMAKE_HOME_DIRECTORY "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_BINDIR "bin" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_DATAROOTDIR "share" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_INCLUDEDIR "include" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_LIBDIR "lib" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_LIBEXECDIR "libexec" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_LOCALSTATEDIR "var" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_OLDINCLUDEDIR "/usr/include" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_PREFIX "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/install" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_SBINDIR "sbin" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_SHAREDSTATEDIR "com" CACHE STRING "" FORCE)
set(CMAKE_INSTALL_SYSCONFDIR "etc" CACHE STRING "" FORCE)
set(CMAKE_MAKE_PROGRAM "C:/MikroElektronika/MikroElektronika/NECTOStudio/bin/ninja.exe" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER "C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/mikroc/arm/mikroc/mikroCARM.exe" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER_FORCED "TRUE" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER_ID "mikroC" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER_ID_RUN "TRUE" CACHE STRING "" FORCE)
set(CMAKE_MikroC_COMPILER_WORKS "TRUE" CACHE STRING "" FORCE)
set(CMAKE_NUMBER_OF_MAKEFILES "1" CACHE STRING "" FORCE)
set(CMAKE_PLATFORM_INFO_INITIALIZED "1" CACHE STRING "" FORCE)
set(CMAKE_PREFIX_PATH "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/install" CACHE STRING "" FORCE)
set(CMAKE_PROJECT_NAME "Main_v1" CACHE STRING "" FORCE)
set(CMAKE_ROOT "C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/CMake/share/cmake-3.30" CACHE STRING "" FORCE)
set(CMAKE_SKIP_INSTALL_RPATH "NO" CACHE STRING "" FORCE)
set(CMAKE_SKIP_RPATH "NO" CACHE STRING "" FORCE)
set(CMAKE_TOOLCHAIN_FILE "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/build-GLCD/toolchain.cmake" CACHE STRING "" FORCE)
set(CMAKE_VERBOSE_MAKEFILE "FALSE" CACHE STRING "" FORCE)
set(CMAKE_mikroC_COMPILER_WORKS "1" CACHE STRING "" FORCE)
set(CORE_LIB "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/lib_core.a" CACHE STRING "" FORCE)
set(CORE_NAME "M3" CACHE STRING "" FORCE)
set(FLATTEN_ME "TRUE" CACHE STRING "" FORCE)
set(FLATTEN_ME_LEVEL "FLATTEN_ME_LEVEL_HIGH" CACHE STRING "" FORCE)
set(HAS_MIKROBUS "true" CACHE STRING "" FORCE)
set(IS_PD_SETUP "FALSE" CACHE STRING "" FORCE)
set(JCFG_FILE "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/STM32F107VC.jcfg" CACHE STRING "" FORCE)
set(LOG_INTERFACE "LOG_INTERFACE_STDOUT" CACHE STRING "" FORCE)
set(MCU_FLASH "262144" CACHE STRING "" FORCE)
set(MCU_NAME "STM32F107VC" CACHE STRING "" FORCE)
set(MCU_RAM "65536" CACHE STRING "" FORCE)
set(MIKROSDK_TYPE "mikrosdk" CACHE STRING "" FORCE)
set(MSDK_BUILD_TFT_MODULES "FALSE" CACHE STRING "" FORCE)
set(Main_v1_BINARY_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/build-GLCD" CACHE STRING "" FORCE)
set(Main_v1_IS_TOP_LEVEL "ON" CACHE STRING "" FORCE)
set(Main_v1_SOURCE_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1" CACHE STRING "" FORCE)
set(MikroC.Core_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroC.Core" CACHE STRING "" FORCE)
set(MikroSDK.Board_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Board" CACHE STRING "" FORCE)
set(MikroSDK.Driver.ADC_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.ADC" CACHE STRING "" FORCE)
set(MikroSDK.Driver.CAN_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.CAN" CACHE STRING "" FORCE)
set(MikroSDK.Driver.DMA_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.DMA" CACHE STRING "" FORCE)
set(MikroSDK.Driver.GPIO.In_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.GPIO.In" CACHE STRING "" FORCE)
set(MikroSDK.Driver.GPIO.Out_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.GPIO.Out" CACHE STRING "" FORCE)
set(MikroSDK.Driver.GPIO.Port_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.GPIO.Port" CACHE STRING "" FORCE)
set(MikroSDK.Driver.I2C.Master_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.I2C.Master" CACHE STRING "" FORCE)
set(MikroSDK.Driver.OneWire_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.OneWire" CACHE STRING "" FORCE)
set(MikroSDK.Driver.PWM_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.PWM" CACHE STRING "" FORCE)
set(MikroSDK.Driver.RTC_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.RTC" CACHE STRING "" FORCE)
set(MikroSDK.Driver.SPI.Master_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.SPI.Master" CACHE STRING "" FORCE)
set(MikroSDK.Driver.UART_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver.UART" CACHE STRING "" FORCE)
set(MikroSDK.Driver_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Driver" CACHE STRING "" FORCE)
set(MikroSDK.GenericPointer_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.GenericPointer" CACHE STRING "" FORCE)
set(MikroSDK.Hal.ADC_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.ADC" CACHE STRING "" FORCE)
set(MikroSDK.Hal.CAN_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.CAN" CACHE STRING "" FORCE)
set(MikroSDK.Hal.DMA_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.DMA" CACHE STRING "" FORCE)
set(MikroSDK.Hal.GPIO_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.GPIO" CACHE STRING "" FORCE)
set(MikroSDK.Hal.I2C.Master_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.I2C.Master" CACHE STRING "" FORCE)
set(MikroSDK.Hal.OneWire_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.OneWire" CACHE STRING "" FORCE)
set(MikroSDK.Hal.PWM_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.PWM" CACHE STRING "" FORCE)
set(MikroSDK.Hal.RTC_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.RTC" CACHE STRING "" FORCE)
set(MikroSDK.Hal.SPI.Master_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.SPI.Master" CACHE STRING "" FORCE)
set(MikroSDK.Hal.UART_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.Hal.UART" CACHE STRING "" FORCE)
set(MikroSDK.HalInterface_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalInterface" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.ADC_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.ADC" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.CAN_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.CAN" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.DMA_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.DMA" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.GPIO_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.GPIO" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.I2C.Master_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.I2C.Master" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.OneWire_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.OneWire" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.RTC_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.RTC" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.SPI.Master_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.SPI.Master" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.TIM_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.TIM" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevel.UART_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevel.UART" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevelCommon_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevelCommon" CACHE STRING "" FORCE)
set(MikroSDK.HalLowLevelCore_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.HalLowLevelCore" CACHE STRING "" FORCE)
set(MikroSDK.MikroBus_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.MikroBus" CACHE STRING "" FORCE)
set(MikroSDK.RingBuffer_DIR "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake/MikroSDK.RingBuffer" CACHE STRING "" FORCE)
set(NECTO_APPLICATION_DIR "C:/MikroElektronika/MikroElektronika/NECTOStudio/bin" CACHE STRING "" FORCE)
set(NECTO_DESIGNER_GENERATOR_PATH "C:/MikroElektronika/MikroElektronika/NECTOStudio/bin/vtft_generator.exe" CACHE STRING "" FORCE)
set(OSC "72" CACHE STRING "" FORCE)
set(PREINIT_ROUTINE_PATH "C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/preinit" CACHE STRING "" FORCE)
set(PROJECT_TYPE "mikrosdk" CACHE STRING "" FORCE)
set(SEARCH_PATHS "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/build-GLCD;C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/core/ARM/mikroC/arm_mikroc_stm32f10_57/def;C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1" CACHE STRING "" FORCE)
set(TEST_LIB_PATH "C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/unit_test_lib" CACHE STRING "" FORCE)
set(TOOLCHAIN_ID "mikrocarm" CACHE STRING "" FORCE)
set(TOOLCHAIN_LANGUAGE "MikroC" CACHE STRING "" FORCE)
set(_GNUInstallDirs_LAST_CMAKE_INSTALL_PREFIX "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/install" CACHE STRING "" FORCE)
set(_HAS_MIKROBUS_ "TRUE" CACHE STRING "" FORCE)
set(_MSDK_BOARD_NAME_ "BOARD_EASYMX_PRO_V7_FOR_STM32" CACHE STRING "" FORCE)
set(_MSDK_ETH_PHY_CHIP_ "&lan8720PhyDriver" CACHE STRING "" FORCE)
set(_MSDK_HAL_LOW_LEVEL_TARGET_ "mikroe" CACHE STRING "" FORCE)
set(_MSDK_MCU_CARD_NAME_ "EASYMX_PRO_V7_FOR_STM32_MCUCARD_WITH_STM32F107VCT6" CACHE STRING "" FORCE)
set(_MSDK_PACKAGE_ID_ "LQFP" CACHE STRING "" FORCE)
set(_MSDK_PACKAGE_NAME_ "Tx" CACHE STRING "" FORCE)
set(_MSDK_PACKAGE_PIN_COUNT_ "100" CACHE STRING "" FORCE)
set(TOOLCHAIN_ID "mikrocarm" CACHE STRING "" FORCE)
set(OSC "72" CACHE STRING "" FORCE)


set(COMPILER_FLAGS -C -SSA -MF -O11111114   "-DBG")
set(LINKER_FLAGS -C -SSA -MF -O11111114   "-DBG")

string(TOLOWER ${CMAKE_BUILD_TYPE} build_type)
if (build_type STREQUAL debug)
    list(APPEND COMPILER_FLAGS "-UICD")
    list(APPEND LINKER_FLAGS "-UICD")
endif()

file(TO_CMAKE_PATH "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/STM32F107VC.jcfg" JCFG_FILE_VAL)
set(JCFG_FILE  ${JCFG_FILE_VAL} CACHE STRING "" FORCE)

file(TO_CMAKE_PATH "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/lib_core.a" CORE_LIB_VAL)
set(CORE_LIB ${CORE_LIB_VAL} CACHE STRING "" FORCE)

set(SEARCH_PATHS "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/build-GLCD;C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/core/ARM/mikroC/arm_mikroc_stm32f10_57/def;C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1" CACHE STRING "" FORCE)

set(CMAKE_MikroC_COMPILER "C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/compilers/mikroc/arm/mikroc/mikroCARM.exe" CACHE INTERNAL "")
set(CMAKE_MikroC_COMPILER_ID "mikroC" CACHE INTERNAL "")

set(CMAKE_MikroC_OUTPUT_EXTENSION_REPLACE 1)
set(CMAKE_MikroC_OUTPUT_EXTENSION ".emcl")

# set CMAKE_SYSTEM_NAME to define build as CMAKE_CROSSCOMPILING
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)

SET(CMAKE_MikroC_COMPILER_WORKS TRUE CACHE INTERNAL "")
SET(CMAKE_MikroC_COMPILER_FORCED TRUE CACHE INTERNAL "")
SET(CMAKE_MikroC_COMPILER_ID_RUN TRUE CACHE INTERNAL "")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

# add compiler option flags
add_compile_options(${COMPILER_FLAGS})
message(INFO ": ${COMPILER_FLAGS}")
# add link option flags
add_link_options(${LINKER_FLAGS})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

file(TO_CMAKE_PATH "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake" MIKROSDK_PATH)
file(TO_CMAKE_PATH "C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake" MIKROC_CORE_PATH)


set(MIKROSDK_ROOT_PATH ${MIKROSDK_PATH})
set(MIKROC_CORE_ROOT_PATH ${MIKROC_CORE_PATH})
#append to cmake_prefix_path
list(APPEND CMAKE_PREFIX_PATH ${MIKROSDK_ROOT_PATH})
list(APPEND CMAKE_PREFIX_PATH ${MIKROC_CORE_ROOT_PATH})

list(APPEND CMAKE_MODULE_PATH "C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/cmake;C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/core/ARM/mikroC/arm_mikroc_stm32f10_57/cmake;C:/Users/SW/AppData/Local/MIKROE/NECTOStudio7/packages/mikroe_utils_common;C:/Users/SW/Desktop/GLCD_Project/middleware/glcd/Main_v1/.meproject/setup/Debug/lib/cmake;")


