if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_APM32E030R_MICROEVB")
    set(BOARD_PATH "include/boards/board_apm32e030r_microevb")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
