if(${_MSDK_BOARD_NAME_} STREQUAL "STARTERKIT_A31G314MMN")
    set(BOARD_PATH "include/boards/board_starterkit_a31g314mmn")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
