if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_LAUNCHPAD_FOR_MSPM0L2228_MCU")
    set(BOARD_PATH "include/boards/board_launchpad_for_mspm0l2228_mcu")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
