if(${_MSDK_BOARD_NAME_} STREQUAL "DSPIC33E_USB_STARTER_KIT_WITH_PIC24EP512GU810")
    set(BOARD_PATH "include/boards/board_dspic33e_usb_starter_kit_with_pic24ep512gu810")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
endif()
