if(${_MSDK_BOARD_NAME_} STREQUAL "NUCLEO_64_WITH_STM32L010RB_MCU")
    set(BOARD_PATH "include/boards/board_nucleo_64_with_stm32l010rb")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
