if(${_MSDK_BOARD_NAME_} STREQUAL "MIKROMEDIA5FORPIC32MZCAPACITIVEFPI")
    set(BOARD_PATH   "include/boards/mikromedia_5_pic32mz_capacitive_fpi")
    set(MCU_CARD  FALSE)
    set(MIKROBUS  FALSE)
endif()
