if(${_MSDK_BOARD_NAME_} STREQUAL "STARTERKIT_A33G527VQN")
    set(BOARD_PATH "include/boards/board_starterkit_a33g527vqn")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
