if(${_MSDK_BOARD_NAME_} STREQUAL "EXPLORER_8_DEVELOPMENT_KIT")
    set(BOARD_PATH "include/boards/board_explorer_8_development_kit")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET TRUE)
endif()
