/*!
 * @file  hal_ll_pior_connection_defs.h
 * @brief PIOR routing map for RL78/L23 (R01UH1082EJ0110 Rev.1.10, Table 4-6).
 *        One row per (pin, function). Scope: SPI(CSI)/UART(SAU+UARTA)/
 *        I2C(SAU+IICA)/Timer(TAU). Analog (ANIx) pins need no PIOR entry -
 *        every one of them shows PIORx = "-" in the manual.
 */

#ifndef _HAL_LL_PIOR_CONNECTION_DEFS_H_
#define _HAL_LL_PIOR_CONNECTION_DEFS_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include "hal_ll_pior_struct_def.h"

// -------------------------------------------------------------

/*!< @brief PIOR ROUTING MAP */
static const hal_ll_pior_pin_map_t hal_ll_pior_map[] =
{
    #ifdef GPIO_PORT_0
    { GPIO_PIN_2, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_2, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 11, 6, 2, 1, false },  /* alt PIOR routing also valid - verify vs other pin assignments */
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_5, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_0, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 10, 6, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_6, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_2, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 11, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_2, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_3, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_0, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_2, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_0, 12, 0, 2, 1, true },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_4, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 10, 6, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_5, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_6, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 11, 2, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_6, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_4, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_0, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_0, 12, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_2, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_1, 12, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_5, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_1, 12, 2, 2, 1, true },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_6, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_7
    { GPIO_PIN_5, GPIO_PORT_7, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_0, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_2, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_4, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_1, 12, 2, 2, 3, true },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_5, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_5, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_3, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_7, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_7, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_1, 12, 2, 2, 2, true },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_0, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_7, 11, 6, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_4, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SCL, HAL_LL_PIOR_MODULE_INDEX_0, 12, 0, 2, 2, true },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_3, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 2, true },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_3, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 11, 6, 2, 1, true },  /* alt PIOR routing also valid - verify vs other pin assignments */
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_6, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 0, true },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_1, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 10, 6, 2, 0, true },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_7, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 0, true },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_6, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 11, 2, 2, 0, true },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_6, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 1, true },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_4, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 2, true },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_1, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_0, 12, 0, 2, 1, true },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_1, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 1, true },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_2, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 2, true },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_3, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 10, 6, 2, 1, true },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_4, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 0, true },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_6, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 11, 6, 2, 0, true },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_7, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 11, 2, 2, 1, true },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_7, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 1, true },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_3, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 0, true },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_1, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_0, 12, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_3, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_1, 12, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_4, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_1, 12, 2, 2, 1, true },
    #endif
    #ifdef GPIO_PORT_7
    { GPIO_PIN_6, GPIO_PORT_7, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 0, true },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_1, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 2, true },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_3, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_1, 12, 2, 2, 3, true },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_6, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 3, true },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_4, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 2, true },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_6, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 3, true },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_6, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_1, 12, 2, 2, 2, true },
    #endif
    #ifdef GPIO_PORT_12
    { GPIO_PIN_5, GPIO_PORT_12, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 1, true },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_5, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_0, 12, 0, 2, 2, true },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_7, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_I2C_SDA, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 1, true },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_3, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_3, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 11, 6, 2, 1, false },  /* alt PIOR routing also valid - verify vs other pin assignments */
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_6, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_1, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 10, 6, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_7, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_6, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 11, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_6, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_4, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_1, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_2, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_3, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 10, 6, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_4, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_6, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 11, 6, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_7, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 11, 2, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_7, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_3, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_7
    { GPIO_PIN_6, GPIO_PORT_7, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_1, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_6, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_4, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_6, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_12
    { GPIO_PIN_5, GPIO_PORT_12, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_7, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MISO, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_0, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_1, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 11, 6, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_4, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_7, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 0, false },  /* alt PIOR routing also valid - verify vs other pin assignments */
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_2, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 10, 6, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_7, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 11, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_7, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_5, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 1, false },  /* alt PIOR routing also valid - verify vs other pin assignments */
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_1, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_2, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_2, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 10, 6, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_3, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_7, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 11, 6, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_2, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_7
    { GPIO_PIN_7, GPIO_PORT_7, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_7, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_5, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 2, false },  /* alt PIOR routing also valid - verify vs other pin assignments */
    #endif
    #ifdef GPIO_PORT_13
    { GPIO_PIN_0, GPIO_PORT_13, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 11, 2, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_13
    { GPIO_PIN_0, GPIO_PORT_13, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_6, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_6, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_MOSI, HAL_LL_PIOR_MODULE_INDEX_7, 11, 6, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_2, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_2, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 11, 6, 2, 1, false },  /* alt PIOR routing also valid - verify vs other pin assignments */
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_5, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_0, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 10, 6, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_6, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_2, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 11, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_2, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_3, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_0, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_4, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 10, 6, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_5, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_6, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 11, 2, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_6, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_4, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_6, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_7
    { GPIO_PIN_5, GPIO_PORT_7, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_0, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 11, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_2, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_5, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 10, 4, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_5, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 11, 4, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_3, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_7, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_1, 10, 2, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_0, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_SPI_SCK, HAL_LL_PIOR_MODULE_INDEX_7, 11, 6, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_1, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_5, 1, 5, 3, 1, false },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_4, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_4, 1, 3, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_5, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_7, 2, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_0, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_0, 0, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_0, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 0, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_1, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 1, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_2, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 0, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_2, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 1, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_3, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 2, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_4, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 3, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_0, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_0, 0, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_1, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_7, 2, 2, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_2, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_5, 1, 5, 3, 0, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_3, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_5, 1, 5, 3, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_4, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_4, 1, 3, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_2, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_0, 0, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_3, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_7, 2, 2, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_4, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_2, 0, 5, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_5, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_2, 0, 5, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_6, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_6, 2, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_7, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 2, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_0, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 4, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_1, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_2, 0, 5, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_2, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 3, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_3, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_4, 1, 3, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_4, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 4, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_5, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_5, 1, 5, 3, 5, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_6, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_5, 1, 5, 3, 3, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_7, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 6, false },
    #endif
    #ifdef GPIO_PORT_7
    { GPIO_PIN_5, GPIO_PORT_7, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 5, false },
    #endif
    #ifdef GPIO_PORT_7
    { GPIO_PIN_7, GPIO_PORT_7, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_7, 2, 2, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_6, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_6, 2, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_0, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_0, 0, 0, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_2, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 5, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_4, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_6, 2, 0, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_5, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_2, 0, 5, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_7, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_5, 1, 5, 3, 4, false },
    #endif
    #ifdef GPIO_PORT_12
    { GPIO_PIN_5, GPIO_PORT_12, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_6, 2, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_12
    { GPIO_PIN_6, GPIO_PORT_12, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_4, 1, 3, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_12
    { GPIO_PIN_7, GPIO_PORT_12, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_IC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 6, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_1, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_5, 1, 5, 3, 1, false },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_4, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_4, 1, 3, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_5, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_7, 2, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_1, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_0, 0, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_0, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 0, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_1, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 1, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_2, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 0, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_2, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 1, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_3, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 2, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_4, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 3, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_0, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_0, 0, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_1, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_7, 2, 2, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_2, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_5, 1, 5, 3, 0, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_3, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_5, 1, 5, 3, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_4, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_4, 1, 3, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_2, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_0, 0, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_3, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_7, 2, 2, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_4, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_2, 0, 5, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_5, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_2, 0, 5, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_6, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_6, 2, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_7, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 2, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_0, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 4, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_1, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_2, 0, 5, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_2, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 3, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_3, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_4, 1, 3, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_4, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 4, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_5, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_5, 1, 5, 3, 5, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_6, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_5, 1, 5, 3, 3, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_7, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 6, false },
    #endif
    #ifdef GPIO_PORT_7
    { GPIO_PIN_5, GPIO_PORT_7, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 5, false },
    #endif
    #ifdef GPIO_PORT_7
    { GPIO_PIN_7, GPIO_PORT_7, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_7, 2, 2, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_6, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_6, 2, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_0, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_0, 0, 0, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_2, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_1, 0, 2, 3, 5, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_4, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_6, 2, 0, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_5, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_2, 0, 5, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_9
    { GPIO_PIN_7, GPIO_PORT_9, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_5, 1, 5, 3, 4, false },
    #endif
    #ifdef GPIO_PORT_12
    { GPIO_PIN_5, GPIO_PORT_12, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_6, 2, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_12
    { GPIO_PIN_6, GPIO_PORT_12, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_4, 1, 3, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_12
    { GPIO_PIN_7, GPIO_PORT_12, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_TIMER_OC, HAL_LL_PIOR_MODULE_INDEX_3, 1, 0, 3, 6, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_3, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_2, 11, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_6, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_1, 10, 4, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_1, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_0, 13, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_7, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_6, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_7, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_1, 13, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_4, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_3, 11, 4, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_1, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_3, 13, 6, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_1, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_1, 10, 4, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_2, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_3, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_1, 13, 2, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_4, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_2, 13, 4, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_4, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_3, 11, 4, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_7, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_0, 13, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_1, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_3, 13, 6, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_7
    { GPIO_PIN_6, GPIO_PORT_7, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_2, 11, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_1, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_1, 10, 4, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_3, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_0, 13, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_6, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_1, 10, 4, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_12
    { GPIO_PIN_5, GPIO_PORT_12, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_3, 11, 4, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_1, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_3, 13, 6, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_2, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_2, 13, 4, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_4, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_1, 13, 2, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_6, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_2, 13, 4, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_7, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_INPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_RX, HAL_LL_PIOR_MODULE_INDEX_2, 11, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_0, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_3, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_2, 13, 4, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_4, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_2, 11, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_0
    { GPIO_PIN_7, GPIO_PORT_0, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_1, 10, 4, 2, 0, false },  /* alt PIOR routing also valid - verify vs other pin assignments */
    #endif
    #ifdef GPIO_PORT_1
    { GPIO_PIN_0, GPIO_PORT_1, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_0, 13, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_6, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_1, 13, 2, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_2
    { GPIO_PIN_7, GPIO_PORT_2, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_3
    { GPIO_PIN_5, GPIO_PORT_3, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_3, 11, 4, 2, 1, false },  /* alt PIOR routing also valid - verify vs other pin assignments */
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_1, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_0, 10, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_2, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_1, 13, 2, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_2, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_1, 10, 4, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_3, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_3, 11, 4, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_4
    { GPIO_PIN_5, GPIO_PORT_4, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_2, 13, 4, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_5
    { GPIO_PIN_0, GPIO_PORT_5, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_3, 13, 6, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_6
    { GPIO_PIN_6, GPIO_PORT_6, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_3, 13, 6, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_7
    { GPIO_PIN_7, GPIO_PORT_7, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_2, 11, 0, 2, 0, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_4, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_0, 13, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_8
    { GPIO_PIN_7, GPIO_PORT_8, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_1, 10, 4, 2, 3, false },
    #endif
    #ifdef GPIO_PORT_13
    { GPIO_PIN_0, GPIO_PORT_13, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_0, 13, 0, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_3, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_2, 13, 4, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_5, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_1, 13, 2, 2, 2, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_6, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_2, 11, 0, 2, 1, false },
    #endif
    #ifdef GPIO_PORT_14
    { GPIO_PIN_7, GPIO_PORT_14, HAL_LL_GPIO_DIGITAL_OUTPUT, HAL_LL_PIOR_FUNCTIONALITY_UART_TX, HAL_LL_PIOR_MODULE_INDEX_3, 13, 6, 2, 2, false },
    #endif

    { HAL_LL_PIN_NC, HAL_LL_PORT_NC, HAL_LL_PIN_NC, HAL_LL_PIOR_FUNCTIONALITY_NONE, HAL_LL_PIN_NC, HAL_LL_PIN_NC, HAL_LL_PIN_NC, HAL_LL_PIN_NC, HAL_LL_PIN_NC, false }
};

#ifdef __cplusplus
}
#endif

#endif // _HAL_LL_PIOR_CONNECTION_DEFS_H_
