if(${MCU_NAME} MATCHES "^STM32G0B1CB$|^STM32G0B1KB$|^STM32G0B1MB$|^STM32G0B1RB$|^STM32G0B1VB$|^STM32G0B1CC$|^STM32G0B1KC$|^STM32G0B1MC$|^STM32G0B1RC$|^STM32G0B1VC$|^STM32G0B1CE$|^STM32G0B1KE$|^STM32G0B1ME$|^STM32G0B1NE$|^STM32G0B1RE$|^STM32G0B1VE$")
    set(adc_subimplementation "${CMAKE_CURRENT_LIST_DIR}/hal_ll_adc.c")
    set(rcc_subimplementation "${CMAKE_CURRENT_SOURCE_DIR}/../../include/rcc/implementations/doc_ds_80")
    set(gpio_subimplementation_include_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../include/gpio/implementations/doc_ds_80")
    list(APPEND hal_ll_def_list "STM32G0xx")
    list(APPEND hal_ll_def_list "STM32G0Bxx")
    list(APPEND hal_ll_def_list "STM32G0B1xx")
    set(adc_pin_map "${CMAKE_CURRENT_SOURCE_DIR}/../../include/adc/hal_ll_adc_pin_map/implementations/doc_ds_80")
    list(APPEND hal_ll_def_list "HAL_LL_ADC_RESOLUTION_CMAKE=HAL_LL_ADC_RESOLUTION_12_BIT")
endif()
