if(${_MSDK_BOARD_NAME_} STREQUAL "MPLAB_STARTER_KIT_FOR_PIC24H_MCUS")
    set(BOARD_PATH "include/boards/board_mplab_starter_kit_for_pic24h_mcus")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
endif()
