/****************************************************************************
**
** Copyright (C) ${COPYRIGHT_YEAR} MikroElektronika d.o.o.
** Contact: https://www.mikroe.com/contact
**
** This file is part of the mikroSDK package
**
** Commercial License Usage
**
** Licensees holding valid commercial NECTO compilers AI licenses may use this
** file in accordance with the commercial license agreement provided with the
** Software or, alternatively, in accordance with the terms contained in
** a written agreement between you and The MikroElektronika Company.
** For licensing terms and conditions see
** https://www.mikroe.com/legal/software-license-agreement.
** For further information use the contact form at
** https://www.mikroe.com/contact.
**
**
** GNU Lesser General Public License Usage
**
** Alternatively, this file may be used for
** non-commercial projects under the terms of the GNU Lesser
** General Public License version 3 as published by the Free Software
** Foundation: https://www.gnu.org/licenses/lgpl-3.0.html.
**
** The above copyright notice and this permission notice shall be
** included in all copies or substantial portions of the Software.
**
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
** EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
** OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
** IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
** DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
** OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
** OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
**
****************************************************************************/
/*!
 * @file  board.h
 * @brief Main board pin mapping.
 */

#ifndef _BOARD_H_
#define _BOARD_H_

#ifdef __cplusplus
extern "C"
{
#endif

#define BOARD_NAME "Evaluation Kit for RA8M2 MCU Group"

#include "mikrobus.h"

// Mapping
#define MIKROBUS_1      1
#define MIKROBUS_1_AN   GPIO_P004
#define MIKROBUS_1_RST  GPIO_P111
#define MIKROBUS_1_CS   GPIO_P414
#define MIKROBUS_1_SCK  GPIO_P415
#define MIKROBUS_1_MISO GPIO_P709
#define MIKROBUS_1_MOSI GPIO_P708
#define MIKROBUS_1_PWM  GPIO_P810
#define MIKROBUS_1_INT  GPIO_P010
#define MIKROBUS_1_RX   GPIO_PC04
#define MIKROBUS_1_TX   GPIO_PC03
#define MIKROBUS_1_SCL  GPIO_P400
#define MIKROBUS_1_SDA  GPIO_P401

#define ARDUINO_CONNECTOR_A0        GPIO_P001
#define ARDUINO_CONNECTOR_A1        GPIO_P007
#define ARDUINO_CONNECTOR_A2        GPIO_P003
#define ARDUINO_CONNECTOR_A3        GPIO_P004
#define ARDUINO_CONNECTOR_A4        GPIO_P014
#define ARDUINO_CONNECTOR_A5        GPIO_P015
#define ARDUINO_CONNECTOR_D0        GPIO_PC04
#define ARDUINO_CONNECTOR_D1        GPIO_PC03
#define ARDUINO_CONNECTOR_D2        GPIO_P011
#define ARDUINO_CONNECTOR_D3        GPIO_P811
#define ARDUINO_CONNECTOR_D4        GPIO_P810
#define ARDUINO_CONNECTOR_D5        GPIO_P510
#define ARDUINO_CONNECTOR_D6        GPIO_P509
#define ARDUINO_CONNECTOR_D7        GPIO_P312
#define ARDUINO_CONNECTOR_D8        GPIO_PD01
#define ARDUINO_CONNECTOR_D9        GPIO_P110
#define ARDUINO_CONNECTOR_D10       GPIO_P414
#define ARDUINO_CONNECTOR_D11       GPIO_P708
#define ARDUINO_CONNECTOR_D12       GPIO_P709
#define ARDUINO_CONNECTOR_D13       GPIO_P415
#define ARDUINO_CONNECTOR_SDA       GPIO_P401
#define ARDUINO_CONNECTOR_SCL       GPIO_P400

#define HEADER_CONNECTOR_J1_D1     GPIO_P
#define HEADER_CONNECTOR_J1_D2     GPIO_P
#define HEADER_CONNECTOR_J1_D3     GPIO_P
#define HEADER_CONNECTOR_J1_D4     GPIO_P
#define HEADER_CONNECTOR_J1_D5     GPIO_P
#define HEADER_CONNECTOR_J1_D6     GPIO_P
#define HEADER_CONNECTOR_J1_D7     GPIO_P
#define HEADER_CONNECTOR_J1_D8     GPIO_P
#define HEADER_CONNECTOR_J1_D9     GPIO_P
#define HEADER_CONNECTOR_J1_D10    GPIO_P
#define HEADER_CONNECTOR_J1_D11    GPIO_P
#define HEADER_CONNECTOR_J1_D12    GPIO_P
#define HEADER_CONNECTOR_J1_D13    GPIO_P
#define HEADER_CONNECTOR_J1_D14    GPIO_P
#define HEADER_CONNECTOR_J1_D15    GPIO_P
#define HEADER_CONNECTOR_J1_D16    GPIO_P
#define HEADER_CONNECTOR_J1_D17    GPIO_P
#define HEADER_CONNECTOR_J1_D18    GPIO_P
#define HEADER_CONNECTOR_J1_D19    GPIO_P
#define HEADER_CONNECTOR_J1_D20    GPIO_P
#define HEADER_CONNECTOR_J1_D21    GPIO_P
#define HEADER_CONNECTOR_J1_D22    GPIO_P
#define HEADER_CONNECTOR_J1_D23    GPIO_P
#define HEADER_CONNECTOR_J1_D24    GPIO_P
#define HEADER_CONNECTOR_J1_D25    GPIO_P
#define HEADER_CONNECTOR_J1_D26    GPIO_P
#define HEADER_CONNECTOR_J1_D27    GPIO_P
#define HEADER_CONNECTOR_J1_D28    GPIO_P
#define HEADER_CONNECTOR_J1_D29    GPIO_P
#define HEADER_CONNECTOR_J1_D30    GPIO_P
#define HEADER_CONNECTOR_J1_D31    GPIO_P
#define HEADER_CONNECTOR_J1_D32    GPIO_P
#define HEADER_CONNECTOR_J1_D33    GPIO_P
#define HEADER_CONNECTOR_J1_D34    GPIO_P
#define HEADER_CONNECTOR_J1_D35    GPIO_P
#define HEADER_CONNECTOR_J1_D36    GPIO_P
#define HEADER_CONNECTOR_J1_D37    GPIO_P
#define HEADER_CONNECTOR_J1_D38    GPIO_P
#define HEADER_CONNECTOR_J1_D39    GPIO_P
#define HEADER_CONNECTOR_J1_D40    GPIO_P

#define HEADER_CONNECTOR_J2_D1     GPIO_P
#define HEADER_CONNECTOR_J2_D2     GPIO_P
#define HEADER_CONNECTOR_J2_D3     GPIO_P
#define HEADER_CONNECTOR_J2_D4     GPIO_P
#define HEADER_CONNECTOR_J2_D5     GPIO_P
#define HEADER_CONNECTOR_J2_D6     GPIO_P
#define HEADER_CONNECTOR_J2_D7     GPIO_P
#define HEADER_CONNECTOR_J2_D8     GPIO_P
#define HEADER_CONNECTOR_J2_D9     GPIO_P
#define HEADER_CONNECTOR_J2_D10    GPIO_P
#define HEADER_CONNECTOR_J2_D11    GPIO_P
#define HEADER_CONNECTOR_J2_D12    GPIO_P
#define HEADER_CONNECTOR_J2_D13    GPIO_P
#define HEADER_CONNECTOR_J2_D14    GPIO_P
#define HEADER_CONNECTOR_J2_D15    GPIO_P
#define HEADER_CONNECTOR_J2_D16    GPIO_P
#define HEADER_CONNECTOR_J2_D17    GPIO_P
#define HEADER_CONNECTOR_J2_D18    GPIO_P
#define HEADER_CONNECTOR_J2_D19    GPIO_P
#define HEADER_CONNECTOR_J2_D20    GPIO_P
#define HEADER_CONNECTOR_J2_D21    GPIO_P
#define HEADER_CONNECTOR_J2_D22    GPIO_P
#define HEADER_CONNECTOR_J2_D23    GPIO_P
#define HEADER_CONNECTOR_J2_D24    GPIO_P
#define HEADER_CONNECTOR_J2_D25    GPIO_P
#define HEADER_CONNECTOR_J2_D26    GPIO_P
#define HEADER_CONNECTOR_J2_D27    GPIO_P
#define HEADER_CONNECTOR_J2_D28    GPIO_P
#define HEADER_CONNECTOR_J2_D29    GPIO_P
#define HEADER_CONNECTOR_J2_D30    GPIO_P
#define HEADER_CONNECTOR_J2_D31    GPIO_P
#define HEADER_CONNECTOR_J2_D32    GPIO_P
#define HEADER_CONNECTOR_J2_D33    GPIO_P
#define HEADER_CONNECTOR_J2_D34    GPIO_P
#define HEADER_CONNECTOR_J2_D35    GPIO_P
#define HEADER_CONNECTOR_J2_D36    GPIO_P
#define HEADER_CONNECTOR_J2_D37    GPIO_P
#define HEADER_CONNECTOR_J2_D38    GPIO_P
#define HEADER_CONNECTOR_J2_D39    GPIO_P
#define HEADER_CONNECTOR_J2_D40    GPIO_P

#define HEADER_CONNECTOR_J3_D1     GPIO_P
#define HEADER_CONNECTOR_J3_D2     GPIO_P
#define HEADER_CONNECTOR_J3_D3     GPIO_P
#define HEADER_CONNECTOR_J3_D4     GPIO_P
#define HEADER_CONNECTOR_J3_D5     GPIO_P
#define HEADER_CONNECTOR_J3_D6     GPIO_P
#define HEADER_CONNECTOR_J3_D7     GPIO_P
#define HEADER_CONNECTOR_J3_D8     GPIO_P
#define HEADER_CONNECTOR_J3_D9     GPIO_P
#define HEADER_CONNECTOR_J3_D10    GPIO_P
#define HEADER_CONNECTOR_J3_D11    GPIO_P
#define HEADER_CONNECTOR_J3_D12    GPIO_P
#define HEADER_CONNECTOR_J3_D13    GPIO_P
#define HEADER_CONNECTOR_J3_D14    GPIO_P
#define HEADER_CONNECTOR_J3_D15    GPIO_P
#define HEADER_CONNECTOR_J3_D16    GPIO_P
#define HEADER_CONNECTOR_J3_D17    GPIO_P
#define HEADER_CONNECTOR_J3_D18    GPIO_P
#define HEADER_CONNECTOR_J3_D19    GPIO_P
#define HEADER_CONNECTOR_J3_D20    GPIO_P
#define HEADER_CONNECTOR_J3_D21    GPIO_P
#define HEADER_CONNECTOR_J3_D22    GPIO_P
#define HEADER_CONNECTOR_J3_D23    GPIO_P
#define HEADER_CONNECTOR_J3_D24    GPIO_P
#define HEADER_CONNECTOR_J3_D25    GPIO_P
#define HEADER_CONNECTOR_J3_D26    GPIO_P
#define HEADER_CONNECTOR_J3_D27    GPIO_P
#define HEADER_CONNECTOR_J3_D28    GPIO_P
#define HEADER_CONNECTOR_J3_D29    GPIO_P
#define HEADER_CONNECTOR_J3_D30    GPIO_P
#define HEADER_CONNECTOR_J3_D31    GPIO_P
#define HEADER_CONNECTOR_J3_D32    GPIO_P
#define HEADER_CONNECTOR_J3_D33    GPIO_P
#define HEADER_CONNECTOR_J3_D34    GPIO_P
#define HEADER_CONNECTOR_J3_D35    GPIO_P
#define HEADER_CONNECTOR_J3_D36    GPIO_P
#define HEADER_CONNECTOR_J3_D37    GPIO_P
#define HEADER_CONNECTOR_J3_D38    GPIO_P
#define HEADER_CONNECTOR_J3_D39    GPIO_P
#define HEADER_CONNECTOR_J3_D40    GPIO_P

#define HEADER_CONNECTOR_J4_D1     GPIO_P
#define HEADER_CONNECTOR_J4_D2     GPIO_P
#define HEADER_CONNECTOR_J4_D3     GPIO_P
#define HEADER_CONNECTOR_J4_D4     GPIO_P
#define HEADER_CONNECTOR_J4_D5     GPIO_P
#define HEADER_CONNECTOR_J4_D6     GPIO_P
#define HEADER_CONNECTOR_J4_D7     GPIO_P
#define HEADER_CONNECTOR_J4_D8     GPIO_P
#define HEADER_CONNECTOR_J4_D9     GPIO_P
#define HEADER_CONNECTOR_J4_D10    GPIO_P
#define HEADER_CONNECTOR_J4_D11    GPIO_P
#define HEADER_CONNECTOR_J4_D12    GPIO_P
#define HEADER_CONNECTOR_J4_D13    GPIO_P
#define HEADER_CONNECTOR_J4_D14    GPIO_P
#define HEADER_CONNECTOR_J4_D15    GPIO_P
#define HEADER_CONNECTOR_J4_D16    GPIO_P
#define HEADER_CONNECTOR_J4_D17    GPIO_P
#define HEADER_CONNECTOR_J4_D18    GPIO_P
#define HEADER_CONNECTOR_J4_D19    GPIO_P
#define HEADER_CONNECTOR_J4_D20    GPIO_P

#define HEADER_CONNECTOR_J14_D1    GPIO_P
#define HEADER_CONNECTOR_J14_D2    GPIO_P
#define HEADER_CONNECTOR_J14_D3    GPIO_P
#define HEADER_CONNECTOR_J14_D4    GPIO_P
#define HEADER_CONNECTOR_J14_D5    GPIO_P
#define HEADER_CONNECTOR_J14_D6    GPIO_P
#define HEADER_CONNECTOR_J14_D7    GPIO_P
#define HEADER_CONNECTOR_J14_D8    GPIO_P
#define HEADER_CONNECTOR_J14_D9    GPIO_P
#define HEADER_CONNECTOR_J14_D10   GPIO_P
#define HEADER_CONNECTOR_J14_D11   GPIO_P
#define HEADER_CONNECTOR_J14_D12   GPIO_P
#define HEADER_CONNECTOR_J14_D13   GPIO_P
#define HEADER_CONNECTOR_J14_D14   GPIO_P
#define HEADER_CONNECTOR_J14_D15   GPIO_P
#define HEADER_CONNECTOR_J14_D16   GPIO_P
#define HEADER_CONNECTOR_J14_D17   GPIO_P
#define HEADER_CONNECTOR_J14_D18   GPIO_P
#define HEADER_CONNECTOR_J14_D19   GPIO_P
#define HEADER_CONNECTOR_J14_D20   GPIO_P
#define HEADER_CONNECTOR_J14_D21   GPIO_P
#define HEADER_CONNECTOR_J14_D22   GPIO_P
#define HEADER_CONNECTOR_J14_D23   GPIO_P
#define HEADER_CONNECTOR_J14_D24   GPIO_P
#define HEADER_CONNECTOR_J14_D25   GPIO_P
#define HEADER_CONNECTOR_J14_D26   GPIO_P

#define HEADER_CONNECTOR_J17_D1    GPIO_P
#define HEADER_CONNECTOR_J17_D2    GPIO_P
#define HEADER_CONNECTOR_J17_D3    GPIO_P
#define HEADER_CONNECTOR_J17_D4    GPIO_P
#define HEADER_CONNECTOR_J17_D5    GPIO_P
#define HEADER_CONNECTOR_J17_D6    GPIO_P
#define HEADER_CONNECTOR_J17_D7    GPIO_P
#define HEADER_CONNECTOR_J17_D8    GPIO_P
#define HEADER_CONNECTOR_J17_D9    GPIO_P
#define HEADER_CONNECTOR_J17_D10   GPIO_P
#define HEADER_CONNECTOR_J17_D11   GPIO_P
#define HEADER_CONNECTOR_J17_D12   GPIO_P
#define HEADER_CONNECTOR_J17_D13   GPIO_P
#define HEADER_CONNECTOR_J17_D14   GPIO_P
#define HEADER_CONNECTOR_J17_D15   GPIO_P
#define HEADER_CONNECTOR_J17_D16   GPIO_P
#define HEADER_CONNECTOR_J17_D17   GPIO_P
#define HEADER_CONNECTOR_J17_D18   GPIO_P
#define HEADER_CONNECTOR_J17_D19   GPIO_P
#define HEADER_CONNECTOR_J17_D20   GPIO_P

#define HEADER_CONNECTOR_J37_D1    GPIO_P
#define HEADER_CONNECTOR_J37_D2    GPIO_P
#define HEADER_CONNECTOR_J37_D3    GPIO_P
#define HEADER_CONNECTOR_J37_D4    GPIO_P
#define HEADER_CONNECTOR_J37_D5    GPIO_P
#define HEADER_CONNECTOR_J37_D6    GPIO_P
#define HEADER_CONNECTOR_J37_D7    GPIO_P
#define HEADER_CONNECTOR_J37_D8    GPIO_P
#define HEADER_CONNECTOR_J37_D9    GPIO_P
#define HEADER_CONNECTOR_J37_D10   GPIO_P
#define HEADER_CONNECTOR_J37_D11   GPIO_P
#define HEADER_CONNECTOR_J37_D12   GPIO_P
#define HEADER_CONNECTOR_J37_D13   GPIO_P
#define HEADER_CONNECTOR_J37_D14   GPIO_P
#define HEADER_CONNECTOR_J37_D15   GPIO_P
#define HEADER_CONNECTOR_J37_D16   GPIO_P
#define HEADER_CONNECTOR_J37_D17   GPIO_P
#define HEADER_CONNECTOR_J37_D18   GPIO_P
#define HEADER_CONNECTOR_J37_D19   GPIO_P
#define HEADER_CONNECTOR_J37_D20   GPIO_P
#define HEADER_CONNECTOR_J37_D21   GPIO_P
#define HEADER_CONNECTOR_J37_D22   GPIO_P
#define HEADER_CONNECTOR_J37_D23   GPIO_P
#define HEADER_CONNECTOR_J37_D24   GPIO_P
#define HEADER_CONNECTOR_J37_D25   GPIO_P
#define HEADER_CONNECTOR_J37_D26   GPIO_P

#define BUTTON1    GPIO_P
#define BUTTON2    GPIO_P

#define LED1       GPIO_P
#define LED2       GPIO_P
#define LED3       GPIO_P

#ifdef __cplusplus
}
#endif

#endif    // _BOARD_H_
// ------------------------------------------------------------------------- END
