if(${_MSDK_BOARD_NAME_} STREQUAL "CLICKER_4_FOR_STM32F745VG")
    set(BOARD_PATH "include/boards/board_clicker_4_for_stm32f745vgt6")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
