if(${_MSDK_BOARD_NAME_} STREQUAL "KIT_EFR32XG24_EXPLORER")
    set(BOARD_PATH "include/boards/board_kit_efr32xg24_explorer")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
