if(${_MSDK_BOARD_NAME_} STREQUAL "STARTERKIT_A31G112CL")
    set(BOARD_PATH "include/boards/board_starterkit_a31g112cl")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
