if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_LPCXPRESSO55S36_DEVELOPMENT")
    set(BOARD_PATH "include/boards/board_lpcxpresso55s36_development")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
