if(${_MSDK_BOARD_NAME_} STREQUAL "NUCLEO_144_WITH_STM32H503RB_MCU")
    set(BOARD_PATH "include/boards/board_nucleo_64_with_stm32h503rb")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
