if(${_MSDK_BOARD_NAME_} STREQUAL "BOARD_LPCXPRESSO_FOR_LPC1549")
    set(BOARD_PATH "include/boards/board_lpcxpresso_for_lpc1549")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
