if(${_MSDK_BOARD_NAME_} STREQUAL "CLICKER_4_FOR_STM32G484VE")
    set(BOARD_PATH "include/boards/clicker_4_for_stm32g484ve")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
