if(${_MSDK_BOARD_NAME_} STREQUAL "SAM_G55_AUDIO_CURIOSITY_DEVELOPMENT_BOARD")
    set(BOARD_PATH "include/boards/board_samg55_audio_curiosity")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
