if(${_MSDK_BOARD_NAME_} STREQUAL "DSPICDEM_MCSM_DEVELOPMENT_BOARD")
    set(BOARD_PATH "include/boards/board_dspicdem_mcsm_development")
    set(PIM_SOCKET TRUE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
