if(${MCU_NAME} MATCHES "^STM32G061C6$|^STM32G061F6$|^STM32G061G6$|^STM32G061K6$|^STM32G061C8$|^STM32G061F8$|^STM32G061G8$|^STM32G061K8$")
    set(tim_subimplementation "${CMAKE_CURRENT_LIST_DIR}/hal_ll_tim.c")
    set(rcc_subimplementation "${CMAKE_CURRENT_SOURCE_DIR}/../../include/rcc/implementations/doc_ds_75")
    set(gpio_subimplementation_include_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../include/gpio/implementations/doc_ds_75")
    list(APPEND hal_ll_def_list "STM32G0xx")
    list(APPEND hal_ll_def_list "STM32G06xx")
    list(APPEND hal_ll_def_list "STM32G061xx")
    set(tim_pin_map "${CMAKE_CURRENT_SOURCE_DIR}/../../include/tim/hal_ll_tim_pin_map/implementations/doc_ds_75")
endif()
