if(${_MSDK_BOARD_NAME_} STREQUAL "STARTERKIT_A31C144RLN")
    set(BOARD_PATH "include/boards/board_starterkit_a31c144rln")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
