function(freertos_get_source_files list_out)
    set(list_local "")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/croutine.c")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/event_groups.c")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/list.c")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/stream_buffer.c")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/tasks.c")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/timers.c")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/queue.c")
    set(${list_out} ${list_local} PARENT_SCOPE)
endfunction()
function(freertos_get_header_files list_out)
    set(list_local "")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/FreeRTOSConfig.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/atomic.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/croutine.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/deprecated_definitions.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/event_groups.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/FreeRTOS.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/list.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/message_buffer.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/mpu_prototypes.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/mpu_syscall_numbers.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/mpu_wrappers.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/newlib-freertos.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/picolibc-freertos.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/portable.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/projdefs.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/queue.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/semphr.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/stack_macros.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/StackMacros.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/stream_buffer.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/task.h")
    list(APPEND list_local "${CMAKE_CURRENT_SOURCE_DIR}/include/timers.h")
    set(${list_out} ${list_local} PARENT_SCOPE )
endfunction()

