/****************************************************************************
**
** Copyright (C) ${COPYRIGHT_YEAR} MikroElektronika d.o.o.
** Contact: https://www.mikroe.com/contact
**
** This file is part of the mikroSDK package
**
** Commercial License Usage
**
** Licensees holding valid commercial NECTO compilers AI licenses may use this
** file in accordance with the commercial license agreement provided with the
** Software or, alternatively, in accordance with the terms contained in
** a written agreement between you and The MikroElektronika Company.
** For licensing terms and conditions see
** https://www.mikroe.com/legal/software-license-agreement.
** For further information use the contact form at
** https://www.mikroe.com/contact.
**
**
** GNU Lesser General Public License Usage
**
** Alternatively, this file may be used for
** non-commercial projects under the terms of the GNU Lesser
** General Public License version 3 as published by the Free Software
** Foundation: https://www.gnu.org/licenses/lgpl-3.0.html.
**
** The above copyright notice and this permission notice shall be
** included in all copies or substantial portions of the Software.
**
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
** EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
** OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
** IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
** DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
** OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
** OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
**
****************************************************************************/
/*!
 * @file  hal_ll_odcon_map.h
 * @brief HAL LOW LEVEL MAP FOR PIN/PORT ODCON REGISTERS.
 */

#ifndef _HAL_LL_ODCON_MAP_H_
#define _HAL_LL_ODCON_MAP_H_

#ifdef __cplusplus
extern "C"{
#endif

#include "hal_ll_pin_names.h"

/*!< @brief Helper macro for getting adequate module index number */
#define hal_ll_module_num(_module_num) (_module_num - 1)

/*!< @brief Macro defining `weak` attribute */
#define __weak __attribute__((weak))

typedef enum
{
    HAL_LL_HW_MODULES_CCP = 0,
    HAL_LL_HW_MODULES_SPI,
    HAL_LL_HW_MODULES_UART,

    HAL_LL_HW_MODULES_DEFAULT = 0xFF
} hal_ll_hw_modules_t;

/*!< @brief Hal low level slew rate map structure. */
typedef struct
{
    hal_ll_pin_name_t pin;
    uint8_t odcon_address_bit;
    uint8_t module_index;
    hal_ll_base_addr_t odcon_address;
    hal_ll_hw_modules_t is_odconx_numeric;
} hal_ll_odconx_t;

/*!< @brief Hal low level map list */
static const hal_ll_odconx_t odconx_map[ HAL_LL_ODCON_BIT_COUNT + 1 ] =
{
    //------------ BEGIN ODCONx
    #ifdef HAL_LL_ODCON_NUMERIC

    //------------ BEGIN ODCON,ODCON1...
    #ifdef HAL_LL_ODCON2_U1OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON2_U1OD_BIT, hal_ll_module_num(UART_MODULE_1), HAL_LL_ODCON2_ADDRESS, HAL_LL_HW_MODULES_UART },
    #endif
    #ifdef HAL_LL_ODCON2_U2OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON2_U2OD_BIT, hal_ll_module_num(UART_MODULE_2), HAL_LL_ODCON2_ADDRESS, HAL_LL_HW_MODULES_UART },
    #endif
    #ifdef HAL_LL_ODCON3_SPI1OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON3_SPI1OD_BIT, hal_ll_module_num(SPI_MODULE_1), HAL_LL_ODCON3_ADDRESS, HAL_LL_HW_MODULES_SPI },
    #endif
    #ifdef HAL_LL_ODCON3_SPI2OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON3_SPI2OD_BIT, hal_ll_module_num(SPI_MODULE_2), HAL_LL_ODCON3_ADDRESS, HAL_LL_HW_MODULES_SPI },
    #endif
    #ifdef HAL_LL_ODCON_U1OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON_U1OD_BIT, hal_ll_module_num(UART_MODULE_1), HAL_LL_ODCON_ADDRESS, HAL_LL_HW_MODULES_UART },
    #endif
    #ifdef HAL_LL_ODCON_U2OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON_U2OD_BIT, hal_ll_module_num(UART_MODULE_2), HAL_LL_ODCON_ADDRESS, HAL_LL_HW_MODULES_UART },
    #endif
    #ifdef HAL_LL_ODCON_CCP1OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON_CCP1OD_BIT, hal_ll_module_num(CCP_MODULE_1), HAL_LL_ODCON_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON_CCP2OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON_CCP2OD_BIT, hal_ll_module_num(CCP_MODULE_2), HAL_LL_ODCON_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON_CCP3OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON_CCP3OD_BIT, hal_ll_module_num(CCP_MODULE_3), HAL_LL_ODCON_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON_CCP4OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON_CCP4OD_BIT, hal_ll_module_num(CCP_MODULE_4), HAL_LL_ODCON_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON_CCP5OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON_CCP5OD_BIT, hal_ll_module_num(CCP_MODULE_5), HAL_LL_ODCON_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON_SSPOD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON_SSPOD_BIT, hal_ll_module_num(SPI_MODULE), HAL_LL_ODCON_ADDRESS, HAL_LL_HW_MODULES_SPI },
    #endif
    #ifdef HAL_LL_ODCON1_CCP4OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_CCP4OD_BIT, hal_ll_module_num(CCP_MODULE_4), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON1_CCP5OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_CCP5OD_BIT, hal_ll_module_num(CCP_MODULE_5), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON1_CCP6OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_CCP6OD_BIT, hal_ll_module_num(CCP_MODULE_6), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON1_CCP7OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_CCP7OD_BIT, hal_ll_module_num(CCP_MODULE_7), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON1_CCP8OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_CCP8OD_BIT, hal_ll_module_num(CCP_MODULE_8), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON2_CCP9OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON2_CCP9OD_BIT, hal_ll_module_num(CCP_MODULE_9), HAL_LL_ODCON2_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON2_CCP10OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON2_CCP10OD_BIT, hal_ll_module_num(CCP_MODULE_10), HAL_LL_ODCON2_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON1_SSP1OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_SSP1OD_BIT, hal_ll_module_num(SPI_MODULE_1), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_SPI },
    #endif
    #ifdef HAL_LL_ODCON1_SSP2OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_SSP2OD_BIT, hal_ll_module_num(SPI_MODULE_2), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_SPI },
    #endif
    #ifdef HAL_LL_ODCON1_USART1OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_USART1OD_BIT, hal_ll_module_num(UART_MODULE_1), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_UART },
    #endif
    #ifdef HAL_LL_ODCON1_USART2OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_USART2OD_BIT, hal_ll_module_num(UART_MODULE_2), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_UART },
    #endif
    #ifdef HAL_LL_ODCON1_USART3OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_USART3OD_BIT, hal_ll_module_num(UART_MODULE_3), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_UART },
    #endif
    #ifdef HAL_LL_ODCON1_USART4OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_USART4OD_BIT, hal_ll_module_num(UART_MODULE_4), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_UART },
    #endif
    #ifdef HAL_LL_ODCON2_CCP4OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON2_CCP4OD_BIT, hal_ll_module_num(CCP_MODULE_4), HAL_LL_ODCON2_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON2_CCP5OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON2_CCP5OD_BIT, hal_ll_module_num(CCP_MODULE_5), HAL_LL_ODCON2_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON2_CCP6OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON2_CCP6OD_BIT, hal_ll_module_num(CCP_MODULE_6), HAL_LL_ODCON2_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON2_CCP7OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON2_CCP7OD_BIT, hal_ll_module_num(CCP_MODULE_7), HAL_LL_ODCON2_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON2_CCP8OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON2_CCP8OD_BIT, hal_ll_module_num(CCP_MODULE_8), HAL_LL_ODCON2_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON1_SPI2OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_SPI2OD_BIT, hal_ll_module_num(SPI_MODULE_2), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_SPI },
    #endif
    #ifdef HAL_LL_ODCON1_CCP1OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_CCP1OD_BIT, hal_ll_module_num(CCP_MODULE_1), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON1_CCP2OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_CCP2OD_BIT, hal_ll_module_num(CCP_MODULE_2), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON1_SPI1OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON1_SPI1OD_BIT, hal_ll_module_num(SPI_MODULE_1), HAL_LL_ODCON1_ADDRESS, HAL_LL_HW_MODULES_SPI },
    #endif
    #ifdef HAL_LL_ODCON2_CCP3OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON2_CCP3OD_BIT, hal_ll_module_num(CCP_MODULE_3), HAL_LL_ODCON2_ADDRESS, HAL_LL_HW_MODULES_CCP },
    #endif
    #ifdef HAL_LL_ODCON3_U1OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON3_U1OD_BIT, hal_ll_module_num(UART_MODULE_1), HAL_LL_ODCON3_ADDRESS, HAL_LL_HW_MODULES_UART },
    #endif
    #ifdef HAL_LL_ODCON3_U2OD_BIT
    { HAL_LL_PIN_NC, HAL_LL_ODCON3_U2OD_BIT, hal_ll_module_num(UART_MODULE_2), HAL_LL_ODCON3_ADDRESS, HAL_LL_HW_MODULES_UART },
    #endif

    //------------ END ODCON, ODCON1...
    #endif

    #ifdef HAL_LL_ODCON_ALPHABETIC

    //------------ BEGIN ODCONA,ODCONB...
    #if defined(HAL_LL_ODCONA_ODCA0_BIT) && defined(GPIO_PA0)
    { GPIO_PA0 , HAL_LL_ODCONA_ODCA0_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONA_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONA_ODCA1_BIT) && defined(GPIO_PA1)
    { GPIO_PA1 , HAL_LL_ODCONA_ODCA1_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONA_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONA_ODCA2_BIT) && defined(GPIO_PA2)
    { GPIO_PA2 , HAL_LL_ODCONA_ODCA2_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONA_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONA_ODCA3_BIT) && defined(GPIO_PA3)
    { GPIO_PA3 , HAL_LL_ODCONA_ODCA3_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONA_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONA_ODCA4_BIT) && defined(GPIO_PA4)
    { GPIO_PA4 , HAL_LL_ODCONA_ODCA4_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONA_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONA_ODCA5_BIT) && defined(GPIO_PA5)
    { GPIO_PA5 , HAL_LL_ODCONA_ODCA5_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONA_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONA_ODCA6_BIT) && defined(GPIO_PA6)
    { GPIO_PA6 , HAL_LL_ODCONA_ODCA6_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONA_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONA_ODCA7_BIT) && defined(GPIO_PA7)
    { GPIO_PA7 , HAL_LL_ODCONA_ODCA7_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONA_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONB_ODCB0_BIT) && defined(GPIO_PB0)
    { GPIO_PB0 , HAL_LL_ODCONB_ODCB0_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONB_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONB_ODCB1_BIT) && defined(GPIO_PB1)
    { GPIO_PB1 , HAL_LL_ODCONB_ODCB1_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONB_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONB_ODCB2_BIT) && defined(GPIO_PB2)
    { GPIO_PB2 , HAL_LL_ODCONB_ODCB2_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONB_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONB_ODCB3_BIT) && defined(GPIO_PB3)
    { GPIO_PB3 , HAL_LL_ODCONB_ODCB3_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONB_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONB_ODCB4_BIT) && defined(GPIO_PB4)
    { GPIO_PB4 , HAL_LL_ODCONB_ODCB4_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONB_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONB_ODCB5_BIT) && defined(GPIO_PB5)
    { GPIO_PB5 , HAL_LL_ODCONB_ODCB5_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONB_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONB_ODCB6_BIT) && defined(GPIO_PB6)
    { GPIO_PB6 , HAL_LL_ODCONB_ODCB6_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONB_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONB_ODCB7_BIT) && defined(GPIO_PB7)
    { GPIO_PB7 , HAL_LL_ODCONB_ODCB7_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONB_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONC_ODCC0_BIT) && defined(GPIO_PC0)
    { GPIO_PC0 , HAL_LL_ODCONC_ODCC0_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONC_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONC_ODCC1_BIT) && defined(GPIO_PC1)
    { GPIO_PC1 , HAL_LL_ODCONC_ODCC1_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONC_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONC_ODCC2_BIT) && defined(GPIO_PC2)
    { GPIO_PC2 , HAL_LL_ODCONC_ODCC2_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONC_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONC_ODCC3_BIT) && defined(GPIO_PC3)
    { GPIO_PC3 , HAL_LL_ODCONC_ODCC3_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONC_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONC_ODCC4_BIT) && defined(GPIO_PC4)
    { GPIO_PC4 , HAL_LL_ODCONC_ODCC4_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONC_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONC_ODCC5_BIT) && defined(GPIO_PC5)
    { GPIO_PC5 , HAL_LL_ODCONC_ODCC5_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONC_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONC_ODCC6_BIT) && defined(GPIO_PC6)
    { GPIO_PC6 , HAL_LL_ODCONC_ODCC6_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONC_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONC_ODCC7_BIT) && defined(GPIO_PC7)
    { GPIO_PC7 , HAL_LL_ODCONC_ODCC7_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONC_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCOND_ODCD0_BIT) && defined(GPIO_PD0)
    { GPIO_PD0 , HAL_LL_ODCOND_ODCD0_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCOND_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCOND_ODCD1_BIT) && defined(GPIO_PD1)
    { GPIO_PD1 , HAL_LL_ODCOND_ODCD1_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCOND_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCOND_ODCD2_BIT) && defined(GPIO_PD2)
    { GPIO_PD2 , HAL_LL_ODCOND_ODCD2_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCOND_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCOND_ODCD3_BIT) && defined(GPIO_PD3)
    { GPIO_PD3 , HAL_LL_ODCOND_ODCD3_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCOND_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCOND_ODCD4_BIT) && defined(GPIO_PD4)
    { GPIO_PD4 , HAL_LL_ODCOND_ODCD4_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCOND_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCOND_ODCD5_BIT) && defined(GPIO_PD5)
    { GPIO_PD5 , HAL_LL_ODCOND_ODCD5_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCOND_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCOND_ODCD6_BIT) && defined(GPIO_PD6)
    { GPIO_PD6 , HAL_LL_ODCOND_ODCD6_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCOND_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCOND_ODCD7_BIT) && defined(GPIO_PD7)
    { GPIO_PD7 , HAL_LL_ODCOND_ODCD7_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCOND_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONE_ODCE0_BIT) && defined(GPIO_PE0)
    { GPIO_PE0 , HAL_LL_ODCONE_ODCE0_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONE_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONE_ODCE1_BIT) && defined(GPIO_PE1)
    { GPIO_PE1 , HAL_LL_ODCONE_ODCE1_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONE_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONE_ODCE2_BIT) && defined(GPIO_PE2)
    { GPIO_PE2 , HAL_LL_ODCONE_ODCE2_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONE_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONF_ODCF0_BIT) && defined(GPIO_PF0)
    { GPIO_PF0 , HAL_LL_ODCONF_ODCF0_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONF_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONF_ODCF1_BIT) && defined(GPIO_PF1)
    { GPIO_PF1 , HAL_LL_ODCONF_ODCF1_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONF_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONF_ODCF2_BIT) && defined(GPIO_PF2)
    { GPIO_PF2 , HAL_LL_ODCONF_ODCF2_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONF_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONF_ODCF3_BIT) && defined(GPIO_PF3)
    { GPIO_PF3 , HAL_LL_ODCONF_ODCF3_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONF_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONF_ODCF4_BIT) && defined(GPIO_PF4)
    { GPIO_PF4 , HAL_LL_ODCONF_ODCF4_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONF_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONF_ODCF5_BIT) && defined(GPIO_PF5)
    { GPIO_PF5 , HAL_LL_ODCONF_ODCF5_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONF_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONF_ODCF6_BIT) && defined(GPIO_PF6)
    { GPIO_PF6 , HAL_LL_ODCONF_ODCF6_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONF_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONF_ODCF7_BIT) && defined(GPIO_PF7)
    { GPIO_PF7 , HAL_LL_ODCONF_ODCF7_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONF_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONE_ODCE3_BIT) && defined(GPIO_PE3)
    { GPIO_PE3 , HAL_LL_ODCONE_ODCE3_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONE_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONE_ODCE4_BIT) && defined(GPIO_PE4)
    { GPIO_PE4 , HAL_LL_ODCONE_ODCE4_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONE_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONE_ODCE5_BIT) && defined(GPIO_PE5)
    { GPIO_PE5 , HAL_LL_ODCONE_ODCE5_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONE_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONE_ODCE6_BIT) && defined(GPIO_PE6)
    { GPIO_PE6 , HAL_LL_ODCONE_ODCE6_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONE_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONE_ODCE7_BIT) && defined(GPIO_PE7)
    { GPIO_PE7 , HAL_LL_ODCONE_ODCE7_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONE_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONG_ODCG0_BIT) && defined(GPIO_PG0)
    { GPIO_PG0 , HAL_LL_ODCONG_ODCG0_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONG_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONG_ODCG1_BIT) && defined(GPIO_PG1)
    { GPIO_PG1 , HAL_LL_ODCONG_ODCG1_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONG_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONG_ODCG2_BIT) && defined(GPIO_PG2)
    { GPIO_PG2 , HAL_LL_ODCONG_ODCG2_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONG_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONG_ODCG3_BIT) && defined(GPIO_PG3)
    { GPIO_PG3 , HAL_LL_ODCONG_ODCG3_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONG_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONG_ODCG4_BIT) && defined(GPIO_PG4)
    { GPIO_PG4 , HAL_LL_ODCONG_ODCG4_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONG_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONG_ODCG6_BIT) && defined(GPIO_PG6)
    { GPIO_PG6 , HAL_LL_ODCONG_ODCG6_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONG_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONG_ODCG7_BIT) && defined(GPIO_PG7)
    { GPIO_PG7 , HAL_LL_ODCONG_ODCG7_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONG_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONH_ODCH0_BIT) && defined(GPIO_PH0)
    { GPIO_PH0 , HAL_LL_ODCONH_ODCH0_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONH_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONH_ODCH1_BIT) && defined(GPIO_PH1)
    { GPIO_PH1 , HAL_LL_ODCONH_ODCH1_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONH_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONH_ODCH2_BIT) && defined(GPIO_PH2)
    { GPIO_PH2 , HAL_LL_ODCONH_ODCH2_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONH_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONH_ODCH3_BIT) && defined(GPIO_PH3)
    { GPIO_PH3 , HAL_LL_ODCONH_ODCH3_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONH_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONH_ODCH4_BIT) && defined(GPIO_PH4)
    { GPIO_PH4 , HAL_LL_ODCONH_ODCH4_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONH_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONH_ODCH5_BIT) && defined(GPIO_PH5)
    { GPIO_PH5 , HAL_LL_ODCONH_ODCH5_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONH_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONH_ODCH6_BIT) && defined(GPIO_PH6)
    { GPIO_PH6 , HAL_LL_ODCONH_ODCH6_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONH_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif
    #if defined(HAL_LL_ODCONH_ODCH7_BIT) && defined(GPIO_PH7)
    { GPIO_PH7 , HAL_LL_ODCONH_ODCH7_BIT, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_ODCONH_ADDRESS, HAL_LL_HW_MODULES_DEFAULT },
    #endif

    //------------ END ODCONA, ODCONB...
    #endif

    //------------ ODCONx LAST ARRAY ELEMENT
    { HAL_LL_PIN_NC, HAL_LL_PIN_NC, HAL_LL_HW_MODULES_DEFAULT, HAL_LL_MODULE_ERROR, HAL_LL_HW_MODULES_DEFAULT }
    //------------ END ODCONx
};

#ifdef __cplusplus
}
#endif

#endif // _HAL_LL_ODCON_MAP_H_
// ------------------------------------------------------------------------- END
