if(${_MSDK_BOARD_NAME_} STREQUAL "KIT_DISCOVERY_WITH_STM32H7B3LI_MCU")
    set(BOARD_PATH "include/boards/board_kit_discovery_with_stm32h7b3li_mcu")
    set(MCU_CARD FALSE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
