if(${_MSDK_BOARD_NAME_} STREQUAL "MIKROMEDIA4FORKINETISCAPACITIVEFPI")
    set(BOARD_PATH   "include/boards/mikromedia_4_kinetis_capacitive_fpi")
    set(MCU_CARD  FALSE)
    set(MIKROBUS  TRUE)
endif()
