if(${_MSDK_BOARD_NAME_} STREQUAL "LCD_EXPLORER_XLP_DEVELOPMENT_BOARD")
    set(BOARD_PATH "include/boards/board_lcd_explorer_xlp_development")
    set(PIM_SOCKET TRUE)
    set(SHIELD FALSE)
    set(DIP_SOCKET FALSE)
endif()
