name: Auto Respond To Contribution

on: pull_request

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v8
        with:
          script: |
            // Get the GitHub username of the PR creator
            const creator = context.payload.sender.login

            // Fetch all issues created by this user in the repository
            const opts = github.rest.issues.listForRepo.endpoint.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator,
              state: 'all'
            })
            const issues = await github.paginate(opts)

            // Check if the creator is a new contributor (no previous PRs)
            for (const issue of issues) {
              if (issue.number === context.issue.number) {
                continue
              }

              if (issue.pull_request) {
                return // Creator is already a contributor with a previous PR.
              }
            }

            // Leave a welcome comment for a new contributor
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Welcome, new contributor! Thanks for contributing.'
            })
