name: Compare Assets between Releases

on:
  workflow_dispatch:
    inputs:
        first_tag:
          type: string
          description: First Release Tag
          default: "latest"
        second_tag:
          type: string
          description: Second Release Tag (specify the tag)
          default: "mikroSDK-2.13.0"

jobs:
  compare-release-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install chardet
          pip install py7zr

      - name: Run Asset Comparation Script
        run: python -u scripts/compare_assets.py ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} "--current_tag" "${{ github.event.inputs.first_tag }}" "--previous_tag" "${{ github.event.inputs.second_tag }}"

      - name: Upload result_compare.txt as artifact
        uses: actions/upload-artifact@v3
        with:
          name: result-compare
          path: result_compare.txt
