name: Prune Released Board Branches

on:
  # Trigger the workflow every Monday at 23:00 UTC
  # Monday to Tuesday at 00:00 ETC
  schedule:
    - cron: '0 22 * * 1'

jobs:
  delete_merged_board_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Authorize Mikroe Actions App
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.MIKROE_ACTIONS }}
          private-key: ${{ secrets.MIKROE_ACTIONS_KEY_AUTHORIZE }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure the full history is fetched to check merged branches.

      - name: Add GitHub Actions credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: List and delete merged feature branches
        run: |
          # Get merged branches and filter those matching 'feature/*'
          branches_to_delete=($(git branch -r --merged | grep 'new-feature/boards' | grep -v 'main' | grep -v 'master' | sed 's/origin\///'))

          # Check if the array is not empty
          if [ ${#branches_to_delete[@]} -eq 0 ]; then
            echo "No branches to delete."
            exit 0
          fi

          # Iterate over the array and delete each branch
          for branch in "${branches_to_delete[@]}"; do
            echo "Deleting branch $branch"
            git push origin --delete "$branch"
          done
