name: Check and update Board to Shield compatibility

on:
  workflow_dispatch

jobs:  
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v6
    - name: Setup permissions
      run: |
        chmod +x ./scripts/BoardToShield/lua/src/lua
        chmod +x ./scripts/BoardToShield/HeaderUpdater/run.sh
        chmod +x ./scripts/BoardToShield/PinMapper/run.sh
        chmod +x ./scripts/BoardToShield/Validator/run.sh
    - name: execute-PinMapper
      run: |
        ./run.sh
      working-directory: ./scripts/BoardToShield/PinMapper
    - name: execute-Validator
      run: |
        ./run.sh
      working-directory: ./scripts/BoardToShield/Validator
    - name: execute-HeaderUpdater
      run: |
        ./run.sh
      working-directory: ./scripts/BoardToShield/HeaderUpdater
    - name: Create a branch and pull request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update board/shield compatibility data
        title: "[Automated] Update board/shield compatibility data"
        body: |
          This PR is automatically created by a GitHub Actions workflow to update the board/shield compatibility data.
        branch: automated-compatibility-updates # Name for the new branch
        base: master # The base branch to merge into
