name: Check and update Board to Shield compatibility

on:
  workflow_dispatch

jobs:  
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v6
    - name: Setup permissions
      run: |
        chmod +x ./scripts/BoardToShield/run.sh
        chmod +x ./scripts/BoardToShield/HeaderUpdater/run.sh
        chmod +x ./scripts/BoardToShield/PinMapper/run.sh
        chmod +x ./scripts/BoardToShield/Validator/run.sh
    - name: execute-script
      run: | 
        ./scripts/BoardToShield/PinMapper/run.sh
        ./scripts/BoardToShield/Validator/run.sh
        ./scripts/BoardToShield/HeaderUpdater/run.sh
